(* Patched for use with FeynCalc *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"SMEFTsim",
  Authors -> {"I. Brivio"},
  Version -> "3.0.1",
  Date -> "January 2021",
  Institutions -> {"ITP, Universitat Heidelberg"},
  Emails -> {"brivio@thphys.uni-heidelberg.de"},
  References -> {"arXiv:1709.06492", "arXiv:2012.11343"},
  URLs -> {"https://feynrules.irmp.ucl.ac.be/wiki/SMEFT", "https://SMEFTsim.github.io"}};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}, {SMHLOOP, 0}, {NP, 0}, {NPshifts, 0}, {NPprop, 0}, {NPcpv, 0}, {NPcbb, 0}, {NPcbB, 0}, {NPcbBB, 0}, {NPcbd1, 0}, {NPcbd8, 0}, {NPcbe, 0}, {NPcbG, 0}, {NPcbH, 0}, {NPcbj1, 0}, {NPcbj8, 0}, {NPcbl, 0}, {NPcbu1, 0}, {NPcbu8, 0}, {NPcbW, 0}, {NPcdB, 0}, {NPcdd1, 0}, {NPcdd8, 0}, {NPcdG, 0}, {NPcdH, 0}, {NPcdW, 0}, {NPceB, 0}, {NPced, 0}, {NPcee, 0}, {NPceH, 0}, {NPceu, 0}, {NPceW, 0}, {NPcG, 0}, {NPcGtil, 0}, {NPcH, 0}, {NPcHB, 0}, {NPcHbox, 0}, {NPcHbq, 0}, {NPcHBtil, 0}, {NPcHd, 0}, {NPcHDD, 0}, {NPcHe, 0}, {NPcHG, 0}, {NPcHGtil, 0}, {NPcHj1, 0}, {NPcHj3, 0}, {NPcHl1, 0}, {NPcHl3, 0}, {NPcHQ1, 0}, {NPcHQ3, 0}, {NPcHt, 0}, {NPcHtb, 0}, {NPcHu, 0}, {NPcHud, 0}, {NPcHW, 0}, {NPcHWB, 0}, {NPcHWBtil, 0}, {NPcHWtil, 0}, {NPcjd1, 0}, {NPcjd8, 0}, {NPcje, 0}, {NPcjj11, 0}, {NPcjj18, 0}, {NPcjj31, 0}, {NPcjj38, 0}, {NPcjQbd1, 0}, {NPcjQbd8, 0}, {NPcjQtu1, 0}, {NPcjQtu8, 0}, {NPcjtQd1, 0}, {NPcjtQd8, 0}, {NPcju1, 0}, {NPcju8, 0}, {NPcjujd1, 0}, {NPcjujd11, 0}, {NPcjujd8, 0}, {NPcjujd81, 0}, {NPcjuQb1, 0}, {NPcjuQb8, 0}, {NPcld, 0}, {NPcle, 0}, {NPclebQ, 0}, {NPcledj, 0}, {NPcleju1, 0}, {NPcleju3, 0}, {NPcleQt1, 0}, {NPcleQt3, 0}, {NPclj1, 0}, {NPclj3, 0}, {NPcll, 0}, {NPcll1, 0}, {NPclu, 0}, {NPcQb1, 0}, {NPcQb8, 0}, {NPcQd1, 0}, {NPcQd8, 0}, {NPcQe, 0}, {NPcQj11, 0}, {NPcQj18, 0}, {NPcQj31, 0}, {NPcQj38, 0}, {NPcQl1, 0}, {NPcQl3, 0}, {NPcQQ1, 0}, {NPcQQ8, 0}, {NPcQt1, 0}, {NPcQt8, 0}, {NPcQtjd1, 0}, {NPcQtjd8, 0}, {NPcQtQb1, 0}, {NPcQtQb8, 0}, {NPcQu1, 0}, {NPcQu8, 0}, {NPcQujb1, 0}, {NPcQujb8, 0}, {NPctB, 0}, {NPctb1, 0}, {NPctb8, 0}, {NPctd1, 0}, {NPctd8, 0}, {NPcte, 0}, {NPctG, 0}, {NPctH, 0}, {NPctj1, 0}, {NPctj8, 0}, {NPctl, 0}, {NPctt, 0}, {NPctu1, 0}, {NPctu8, 0}, {NPctW, 0}, {NPcuB, 0}, {NPcud1, 0}, {NPcud8, 0}, {NPcuG, 0}, {NPcuH, 0}, {NPcutbd1, 0}, {NPcutbd8, 0}, {NPcuu1, 0}, {NPcuu8, 0}, {NPcuW, 0}, {NPcW, 0}, {NPcWtil, 0}, {NPQjujb8, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Generation2] ] = Range[ 2 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "a",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Z",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> FCGV["MZ"],
    Indices -> {} },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "W",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MW"],
    Indices -> {} },

V[4] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uA",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {} },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uZ",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MZ"],
    Indices -> {} },

U[31] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorLabel -> "uWp",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MW"],
    Indices -> {} },

U[32] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorLabel -> "uWm",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MW"],
    Indices -> {} },

U[4] == {
    SelfConjugate -> False,
    Indices -> {Index[Gluon]},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uG",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

V[13] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Superscript[Z,,]",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ1,
    Indices -> {} },

V[14] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "Superscript[W,,]",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW1,
    Indices -> {} },

F[1] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[2] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Ml },

F[3] == {
    Indices -> {Index[Generation2], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "uq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mu },

F[30] == {
    Indices -> {Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "t",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MT"] },

F[4] == {
    Indices -> {Index[Generation2], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorLabel -> "dq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Md },

F[40] == {
    Indices -> {Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorLabel -> "b",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MB"] },

F[31] == {
    Indices -> {Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "Superscript[t,,]",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MT1 },

S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "H",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> FCGV["MH"],
    Indices -> {} },

S[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Go",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> FCGV["MZ"],
    Indices -> {} },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "GP",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> FCGV["MW"],
    Indices -> {} },

S[4] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Superscript[H,,]",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH1,
    Indices -> {} }
}


(*        Definitions       *)

FAGaugeXi[ V[1] ] = FAGaugeXi[A];
FAGaugeXi[ V[2] ] = FAGaugeXi[Z];
FAGaugeXi[ V[3] ] = FAGaugeXi[W];
FAGaugeXi[ V[4] ] = FAGaugeXi[G];
FAGaugeXi[ U[1] ] = FAGaugeXi[A];
FAGaugeXi[ U[2] ] = FAGaugeXi[Z];
FAGaugeXi[ U[31] ] = FAGaugeXi[W];
FAGaugeXi[ U[32] ] = FAGaugeXi[W];
FAGaugeXi[ U[4] ] = FAGaugeXi[G];
FAGaugeXi[ S[1] ] = 1;
FAGaugeXi[ S[2] ] = FAGaugeXi[Z];
FAGaugeXi[ S[3] ] = FAGaugeXi[W];

FCGV["MZ"][ ___ ] := FCGV["MZ"];
FCGV["MW"][ ___ ] := FCGV["MW"];
MZ1[ ___ ] := MZ1;
MW1[ ___ ] := MW1;
Ml[ 1 ] := Me;
Ml[ 2 ] := MMU;
Ml[ 3 ] := MTA;
Mu[ 1, _ ] := FCGV["MU"];
Mu[ 1 ] := FCGV["MU"];
Mu[ 2, _ ] := FCGV["MC"];
Mu[ 2 ] := FCGV["MC"];
FCGV["MT"][ ___ ] := FCGV["MT"];
Md[ 1, _ ] := FCGV["MD"];
Md[ 1 ] := FCGV["MD"];
Md[ 2, _ ] := FCGV["MS"];
Md[ 2 ] := FCGV["MS"];
FCGV["MB"][ ___ ] := FCGV["MB"];
MT1[ ___ ] := MT1;
FCGV["MH"][ ___ ] := FCGV["MH"];
MH1[ ___ ] := MH1;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[4, {__}] ] := TheLabel[U[4]];
TheLabel[ F[1, {1}] ] := "ve";
TheLabel[ F[1, {2}] ] := "vm";
TheLabel[ F[1, {3}] ] := "vt";
TheLabel[ F[2, {1}] ] := "e";
TheLabel[ F[2, {2}] ] := "mu";
TheLabel[ F[2, {3}] ] := "ta";
TheLabel[ F[3, {1, _}] ] := "u";
TheLabel[ F[3, {1}] ] := "u";
TheLabel[ F[3, {2, _}] ] := "c";
TheLabel[ F[3, {2}] ] := "c";
TheLabel[ F[30, {__}] ] := TheLabel[F[30]];
TheLabel[ F[4, {1, _}] ] := "d";
TheLabel[ F[4, {1}] ] := "d";
TheLabel[ F[4, {2, _}] ] := "s";
TheLabel[ F[4, {2}] ] := "s";
TheLabel[ F[40, {__}] ] := TheLabel[F[40]];
TheLabel[ F[31, {__}] ] := TheLabel[F[31]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[1] , S[1] , S[1] , S[1] ] == {{((6*I)*lam*(-1 + sth)*(1 + sth))/cth^2, 0}},

C[ S[1] , S[1] , S[1] ] == {{((6*I)*lam*(-1 + sth)*(1 + sth)*vevhat)/cth^2, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc3*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc3*FASUNF[e1x2, e2x2, e3x2], 0}, {gc3*FASUNF[e1x2, e2x2, e3x2], 0}, {-(gc3*FASUNF[e1x2, e2x2, e3x2]), 0}, {-(gc3*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc3*FASUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc4*(FASUNF[e1x2, e2x2, e3x2, e4x2] + FASUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc4*(FASUNF[e1x2, e2x2, e3x2, e4x2] - FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc4*(FASUNF[e1x2, e3x2, e2x2, e4x2] + FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ -F[40, {e1x2}] , F[40, {e2x2}] , V[1] ] == {{I*gc5*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {I*gc5*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(3*gc5*(-(cbBIm*cth) - I*cbBRe*cth + (cbWIm + I*cbWRe)*sth)*vevhat*IndexDelta[e1x2, e2x2])/(Sqrt[2]*FCGV["EL"]*LambdaSMEFT^2), 0}, {0, 0}, {(3*gc5*(cbBIm*cth - I*cbBRe*cth - cbWIm*sth + I*cbWRe*sth)*vevhat*IndexDelta[e1x2, e2x2])/(Sqrt[2]*FCGV["EL"]*LambdaSMEFT^2), 0}, {0, 0}, {(3*gc5*(cbBIm*cth + I*cbBRe*cth - cbWIm*sth - I*cbWRe*sth)*vevhat*IndexDelta[e1x2, e2x2])/(Sqrt[2]*FCGV["EL"]*LambdaSMEFT^2), 0}, {0, 0}, {(3*gc5*(-(cbBIm*cth) + I*cbBRe*cth + (cbWIm - I*cbWRe)*sth)*vevhat*IndexDelta[e1x2, e2x2])/(Sqrt[2]*FCGV["EL"]*LambdaSMEFT^2), 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[1] ] == {{I*gc6*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}, {I*gc6*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}, {(3*gc6*(-(cdBIm*cth) - I*cdBRe*cth + (cdWIm + I*cdWRe)*sth)*vevhat*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2])/(Sqrt[2]*FCGV["EL"]*LambdaSMEFT^2), 0}, {0, 0}, {(3*gc6*(cdBIm*cth - I*cdBRe*cth - cdWIm*sth + I*cdWRe*sth)*vevhat*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2])/(Sqrt[2]*FCGV["EL"]*LambdaSMEFT^2), 0}, {0, 0}, {(3*gc6*(cdBIm*cth + I*cdBRe*cth - cdWIm*sth - I*cdWRe*sth)*vevhat*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2])/(Sqrt[2]*FCGV["EL"]*LambdaSMEFT^2), 0}, {0, 0}, {(3*gc6*(-(cdBIm*cth) + I*cdBRe*cth + (cdWIm - I*cdWRe)*sth)*vevhat*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2])/(Sqrt[2]*FCGV["EL"]*LambdaSMEFT^2), 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[1] ] == {{I*gc7*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {I*gc7*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(gc7*(-(ceBIm*cth) - I*ceBRe*cth + (ceWIm + I*ceWRe)*sth)*vevhat*yl[e1x2, e2x2])/(Sqrt[2]*FCGV["EL"]*LambdaSMEFT^2), 0}, {0, 0}, {(gc7*(ceBIm*cth - I*ceBRe*cth - ceWIm*sth + I*ceWRe*sth)*vevhat*yl[e2x2, e1x2])/(Sqrt[2]*FCGV["EL"]*LambdaSMEFT^2), 0}, {0, 0}, {(gc7*(ceBIm*cth + I*ceBRe*cth - ceWIm*sth - I*ceWRe*sth)*vevhat*yl[e1x2, e2x2])/(Sqrt[2]*FCGV["EL"]*LambdaSMEFT^2), 0}, {0, 0}, {(gc7*(-(ceBIm*cth) + I*ceBRe*cth + (ceWIm - I*ceWRe)*sth)*vevhat*yl[e2x2, e1x2])/(Sqrt[2]*FCGV["EL"]*LambdaSMEFT^2), 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[30, {e2x2}] , V[1] ] == {{I*gc8*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {I*gc8*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(3*gc8*(ctBIm*cth + I*ctBRe*cth + (ctWIm + I*ctWRe)*sth)*vevhat*IndexDelta[e1x2, e2x2])/(2*Sqrt[2]*FCGV["EL"]*LambdaSMEFT^2), 0}, {0, 0}, {(-3*gc8*(ctBIm*cth - I*ctBRe*cth + (ctWIm - I*ctWRe)*sth)*vevhat*IndexDelta[e1x2, e2x2])/(2*Sqrt[2]*FCGV["EL"]*LambdaSMEFT^2), 0}, {0, 0}, {(-3*gc8*(ctBIm*cth + I*ctBRe*cth + (ctWIm + I*ctWRe)*sth)*vevhat*IndexDelta[e1x2, e2x2])/(2*Sqrt[2]*FCGV["EL"]*LambdaSMEFT^2), 0}, {0, 0}, {(3*gc8*(ctBIm*cth - I*ctBRe*cth + (ctWIm - I*ctWRe)*sth)*vevhat*IndexDelta[e1x2, e2x2])/(2*Sqrt[2]*FCGV["EL"]*LambdaSMEFT^2), 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[1] ] == {{I*gc9*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}, {I*gc9*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}, {(3*gc9*(cth*(cuBIm + I*cuBRe) + (cuWIm + I*cuWRe)*sth)*vevhat*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2])/(2*Sqrt[2]*FCGV["EL"]*LambdaSMEFT^2), 0}, {0, 0}, {(-3*gc9*(cth*(cuBIm - I*cuBRe) + (cuWIm - I*cuWRe)*sth)*vevhat*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2])/(2*Sqrt[2]*FCGV["EL"]*LambdaSMEFT^2), 0}, {0, 0}, {(-3*gc9*(cth*(cuBIm + I*cuBRe) + (cuWIm + I*cuWRe)*sth)*vevhat*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2])/(2*Sqrt[2]*FCGV["EL"]*LambdaSMEFT^2), 0}, {0, 0}, {(3*gc9*(cth*(cuBIm - I*cuBRe) + (cuWIm - I*cuWRe)*sth)*vevhat*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2])/(2*Sqrt[2]*FCGV["EL"]*LambdaSMEFT^2), 0}, {0, 0}},

C[ -F[40, {e1x2}] , F[40, {e2x2}] , S[1] ] == {{I*gc10*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {I*gc10*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[30, {e2x2}] , S[1] ] == {{I*gc11*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {I*gc11*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc12, 0}, {I*gc12, 0}, {I*gc12, 0}, {(-I)*gc12, 0}, {(-I)*gc12, 0}, {I*gc12, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((-I/2)*FCGV["EL"]^2*(-1 + sth)*(1 + sth))/(cth^2*sth^2), 0}},

C[ S[1] , V[3] , -V[3] ] == {{((-I/2)*FCGV["EL"]^2*(-1 + sth)*(1 + sth)*vevhat)/(cth^2*sth^2), 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc15, 0}, {(-I)*gc15, 0}, {(2*I)*gc15, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc16, 0}, {I*gc16, 0}, {I*gc16, 0}, {(-I)*gc16, 0}, {(-I)*gc16, 0}, {I*gc16, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc17, 0}, {(-I)*gc17, 0}, {(2*I)*gc17, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] ] == {{I*gc18[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}, {(I*gc18[e1x2, e2x2]*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2])/ydtop[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[1] ] == {{I*gc19[e1x2, e2x2], 0}, {0, 0}, {(I*gc19[e1x2, e2x2]*yl[e2x2, e1x2])/yl[e1x2, e2x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] ] == {{I*gc20[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}, {(I*gc20[e1x2, e2x2]*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2])/yutop[e1x2, e2x2], 0}, {0, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc21, 0}, {I*gc21, 0}, {I*gc21, 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2)/(cth^2*sth^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*vevhat)/(cth^2*sth^2), 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc24, 0}, {(-I)*gc24, 0}, {(2*I)*gc24, 0}},

C[ -F[40, {e1x2}] , F[40, {e2x2}] , V[4, {e3x2}] ] == {{I*gc25*FASUNT[e3x2, e1x2, e2x2], 0}, {0, 0}, {I*gc25*FASUNT[e3x2, e1x2, e2x2], 0}, {0, 0}, {((cbGIm + I*cbGRe)*gc25*vevhat*FASUNT[e3x2, e1x2, e2x2])/(Sqrt[2]*FAGS*LambdaSMEFT^2), 0}, {0, 0}, {-(((cbGIm - I*cbGRe)*gc25*vevhat*FASUNT[e3x2, e1x2, e2x2])/(Sqrt[2]*FAGS*LambdaSMEFT^2)), 0}, {0, 0}, {-(((cbGIm + I*cbGRe)*gc25*vevhat*FASUNT[e3x2, e1x2, e2x2])/(Sqrt[2]*FAGS*LambdaSMEFT^2)), 0}, {0, 0}, {((cbGIm - I*cbGRe)*gc25*vevhat*FASUNT[e3x2, e1x2, e2x2])/(Sqrt[2]*FAGS*LambdaSMEFT^2), 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc26*IndexDelta[e1x2, e2x2]*FASUNT[e3x2, e1x3, e2x3], 0}, {0, 0}, {I*gc26*IndexDelta[e1x2, e2x2]*FASUNT[e3x2, e1x3, e2x3], 0}, {0, 0}, {((cdGIm + I*cdGRe)*gc26*vevhat*FASUNT[e3x2, e1x3, e2x3]*ydtop[e1x2, e2x2])/(Sqrt[2]*FAGS*LambdaSMEFT^2), 0}, {0, 0}, {-(((cdGIm - I*cdGRe)*gc26*vevhat*FASUNT[e3x2, e1x3, e2x3]*ydtop[e2x2, e1x2])/(Sqrt[2]*FAGS*LambdaSMEFT^2)), 0}, {0, 0}, {-(((cdGIm + I*cdGRe)*gc26*vevhat*FASUNT[e3x2, e1x3, e2x3]*ydtop[e1x2, e2x2])/(Sqrt[2]*FAGS*LambdaSMEFT^2)), 0}, {0, 0}, {((cdGIm - I*cdGRe)*gc26*vevhat*FASUNT[e3x2, e1x3, e2x3]*ydtop[e2x2, e1x2])/(Sqrt[2]*FAGS*LambdaSMEFT^2), 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[30, {e2x2}] , V[4, {e3x2}] ] == {{I*gc27*FASUNT[e3x2, e1x2, e2x2], 0}, {0, 0}, {I*gc27*FASUNT[e3x2, e1x2, e2x2], 0}, {0, 0}, {((ctGIm + I*ctGRe)*gc27*vevhat*FASUNT[e3x2, e1x2, e2x2])/(Sqrt[2]*FAGS*LambdaSMEFT^2), 0}, {0, 0}, {-(((ctGIm - I*ctGRe)*gc27*vevhat*FASUNT[e3x2, e1x2, e2x2])/(Sqrt[2]*FAGS*LambdaSMEFT^2)), 0}, {0, 0}, {-(((ctGIm + I*ctGRe)*gc27*vevhat*FASUNT[e3x2, e1x2, e2x2])/(Sqrt[2]*FAGS*LambdaSMEFT^2)), 0}, {0, 0}, {((ctGIm - I*ctGRe)*gc27*vevhat*FASUNT[e3x2, e1x2, e2x2])/(Sqrt[2]*FAGS*LambdaSMEFT^2), 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc28*IndexDelta[e1x2, e2x2]*FASUNT[e3x2, e1x3, e2x3], 0}, {0, 0}, {I*gc28*IndexDelta[e1x2, e2x2]*FASUNT[e3x2, e1x3, e2x3], 0}, {0, 0}, {((cuGIm + I*cuGRe)*gc28*vevhat*FASUNT[e3x2, e1x3, e2x3]*yutop[e1x2, e2x2])/(Sqrt[2]*FAGS*LambdaSMEFT^2), 0}, {0, 0}, {-(((cuGIm - I*cuGRe)*gc28*vevhat*FASUNT[e3x2, e1x3, e2x3]*yutop[e2x2, e1x2])/(Sqrt[2]*FAGS*LambdaSMEFT^2)), 0}, {0, 0}, {-(((cuGIm + I*cuGRe)*gc28*vevhat*FASUNT[e3x2, e1x3, e2x3]*yutop[e1x2, e2x2])/(Sqrt[2]*FAGS*LambdaSMEFT^2)), 0}, {0, 0}, {((cuGIm - I*cuGRe)*gc28*vevhat*FASUNT[e3x2, e1x3, e2x3]*yutop[e2x2, e1x2])/(Sqrt[2]*FAGS*LambdaSMEFT^2), 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[40, {e2x2}] , V[3] ] == {{I*gc29*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {(Sqrt[2]*(ctWIm + I*ctWRe)*gc29*sth*vevhat*IndexDelta[e1x2, e2x2])/(FCGV["EL"]*LambdaSMEFT^2), 0}, {0, 0}, {-((Sqrt[2]*(cbWIm - I*cbWRe)*gc29*sth*vevhat*IndexDelta[e1x2, e2x2])/(FCGV["EL"]*LambdaSMEFT^2)), 0}, {0, 0}, {-((Sqrt[2]*(ctWIm + I*ctWRe)*gc29*sth*vevhat*IndexDelta[e1x2, e2x2])/(FCGV["EL"]*LambdaSMEFT^2)), 0}, {0, 0}, {(Sqrt[2]*(cbWIm - I*cbWRe)*gc29*sth*vevhat*IndexDelta[e1x2, e2x2])/(FCGV["EL"]*LambdaSMEFT^2), 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[3] ] == {{I*gc30*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}, {0, 0}, {0, 0}, {(Sqrt[2]*(cuWIm + I*cuWRe)*gc30*sth*vevhat*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2])/(FCGV["EL"]*LambdaSMEFT^2), 0}, {0, 0}, {-((Sqrt[2]*(cdWIm - I*cdWRe)*gc30*sth*vevhat*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2])/(FCGV["EL"]*LambdaSMEFT^2)), 0}, {0, 0}, {-((Sqrt[2]*(cuWIm + I*cuWRe)*gc30*sth*vevhat*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2])/(FCGV["EL"]*LambdaSMEFT^2)), 0}, {0, 0}, {(Sqrt[2]*(cdWIm - I*cdWRe)*gc30*sth*vevhat*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2])/(FCGV["EL"]*LambdaSMEFT^2), 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , V[3] ] == {{I*gc31*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {-((Sqrt[2]*(ceWIm - I*ceWRe)*gc31*sth*vevhat*yl[e2x2, e1x2])/(FCGV["EL"]*LambdaSMEFT^2)), 0}, {0, 0}, {0, 0}, {0, 0}, {(Sqrt[2]*(ceWIm - I*ceWRe)*gc31*sth*vevhat*yl[e2x2, e1x2])/(FCGV["EL"]*LambdaSMEFT^2), 0}, {0, 0}},

C[ -F[40, {e1x2}] , F[30, {e2x2}] , -V[3] ] == {{I*gc32*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {(Sqrt[2]*(cbWIm + I*cbWRe)*gc32*sth*vevhat*IndexDelta[e1x2, e2x2])/(FCGV["EL"]*LambdaSMEFT^2), 0}, {0, 0}, {-((Sqrt[2]*(ctWIm - I*ctWRe)*gc32*sth*vevhat*IndexDelta[e1x2, e2x2])/(FCGV["EL"]*LambdaSMEFT^2)), 0}, {0, 0}, {-((Sqrt[2]*(cbWIm + I*cbWRe)*gc32*sth*vevhat*IndexDelta[e1x2, e2x2])/(FCGV["EL"]*LambdaSMEFT^2)), 0}, {0, 0}, {(Sqrt[2]*(ctWIm - I*ctWRe)*gc32*sth*vevhat*IndexDelta[e1x2, e2x2])/(FCGV["EL"]*LambdaSMEFT^2), 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -V[3] ] == {{I*gc33*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}, {0, 0}, {0, 0}, {(Sqrt[2]*(cdWIm + I*cdWRe)*gc33*sth*vevhat*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2])/(FCGV["EL"]*LambdaSMEFT^2), 0}, {0, 0}, {-((Sqrt[2]*(cuWIm - I*cuWRe)*gc33*sth*vevhat*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2])/(FCGV["EL"]*LambdaSMEFT^2)), 0}, {0, 0}, {-((Sqrt[2]*(cdWIm + I*cdWRe)*gc33*sth*vevhat*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2])/(FCGV["EL"]*LambdaSMEFT^2)), 0}, {0, 0}, {(Sqrt[2]*(cuWIm - I*cuWRe)*gc33*sth*vevhat*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2])/(FCGV["EL"]*LambdaSMEFT^2), 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -V[3] ] == {{I*gc34*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {(Sqrt[2]*(ceWIm + I*ceWRe)*gc34*sth*vevhat*yl[e1x2, e2x2])/(FCGV["EL"]*LambdaSMEFT^2), 0}, {0, 0}, {0, 0}, {0, 0}, {-((Sqrt[2]*(ceWIm + I*ceWRe)*gc34*sth*vevhat*yl[e1x2, e2x2])/(FCGV["EL"]*LambdaSMEFT^2)), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[40, {e1x2}] , F[40, {e2x2}] , V[2] ] == {{I*gc35*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {((2*I)*gc35*sth^2*IndexDelta[e1x2, e2x2])/(-3 + 2*sth^2), 0}, {0, 0}, {(-3*Sqrt[2]*cth*gc35*sth*(cbWIm*cth + I*cbWRe*cth + (cbBIm + I*cbBRe)*sth)*vevhat*IndexDelta[e1x2, e2x2])/(FCGV["EL"]*LambdaSMEFT^2*(-3 + 2*sth^2)), 0}, {0, 0}, {(3*Sqrt[2]*cth*gc35*sth*(cbWIm*cth - I*cbWRe*cth + (cbBIm - I*cbBRe)*sth)*vevhat*IndexDelta[e1x2, e2x2])/(FCGV["EL"]*LambdaSMEFT^2*(-3 + 2*sth^2)), 0}, {0, 0}, {(3*Sqrt[2]*cth*gc35*sth*(cbWIm*cth + I*cbWRe*cth + (cbBIm + I*cbBRe)*sth)*vevhat*IndexDelta[e1x2, e2x2])/(FCGV["EL"]*LambdaSMEFT^2*(-3 + 2*sth^2)), 0}, {0, 0}, {(-3*Sqrt[2]*cth*gc35*sth*(cbWIm*cth - I*cbWRe*cth + (cbBIm - I*cbBRe)*sth)*vevhat*IndexDelta[e1x2, e2x2])/(FCGV["EL"]*LambdaSMEFT^2*(-3 + 2*sth^2)), 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[2] ] == {{I*gc36*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}, {((2*I)*gc36*sth^2*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3])/(-3 + 2*sth^2), 0}, {0, 0}, {(-3*Sqrt[2]*cth*gc36*sth*(cdWIm*cth + I*cdWRe*cth + (cdBIm + I*cdBRe)*sth)*vevhat*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2])/(FCGV["EL"]*LambdaSMEFT^2*(-3 + 2*sth^2)), 0}, {0, 0}, {(3*Sqrt[2]*cth*gc36*sth*(cdWIm*cth - I*cdWRe*cth + (cdBIm - I*cdBRe)*sth)*vevhat*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2])/(FCGV["EL"]*LambdaSMEFT^2*(-3 + 2*sth^2)), 0}, {0, 0}, {(3*Sqrt[2]*cth*gc36*sth*(cdWIm*cth + I*cdWRe*cth + (cdBIm + I*cdBRe)*sth)*vevhat*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2])/(FCGV["EL"]*LambdaSMEFT^2*(-3 + 2*sth^2)), 0}, {0, 0}, {(-3*Sqrt[2]*cth*gc36*sth*(cdWIm*cth - I*cdWRe*cth + (cdBIm - I*cdBRe)*sth)*vevhat*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2])/(FCGV["EL"]*LambdaSMEFT^2*(-3 + 2*sth^2)), 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[2] ] == {{I*gc37*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {((2*I)*gc37*sth^2*IndexDelta[e1x2, e2x2])/(-1 + 2*sth^2), 0}, {0, 0}, {-((Sqrt[2]*cth*gc37*sth*(ceWIm*cth + I*ceWRe*cth + (ceBIm + I*ceBRe)*sth)*vevhat*yl[e1x2, e2x2])/(FCGV["EL"]*LambdaSMEFT^2*(-1 + 2*sth^2))), 0}, {0, 0}, {(Sqrt[2]*cth*gc37*sth*(ceWIm*cth - I*ceWRe*cth + (ceBIm - I*ceBRe)*sth)*vevhat*yl[e2x2, e1x2])/(FCGV["EL"]*LambdaSMEFT^2*(-1 + 2*sth^2)), 0}, {0, 0}, {(Sqrt[2]*cth*gc37*sth*(ceWIm*cth + I*ceWRe*cth + (ceBIm + I*ceBRe)*sth)*vevhat*yl[e1x2, e2x2])/(FCGV["EL"]*LambdaSMEFT^2*(-1 + 2*sth^2)), 0}, {0, 0}, {-((Sqrt[2]*cth*gc37*sth*(ceWIm*cth - I*ceWRe*cth + (ceBIm - I*ceBRe)*sth)*vevhat*yl[e2x2, e1x2])/(FCGV["EL"]*LambdaSMEFT^2*(-1 + 2*sth^2))), 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[30, {e2x2}] , V[2] ] == {{I*gc38*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {((4*I)*gc38*sth^2*IndexDelta[e1x2, e2x2])/(-3 + 4*sth^2), 0}, {0, 0}, {(-3*Sqrt[2]*cth*gc38*sth*(cth*(ctWIm + I*ctWRe) - (ctBIm + I*ctBRe)*sth)*vevhat*IndexDelta[e1x2, e2x2])/(FCGV["EL"]*LambdaSMEFT^2*(-3 + 4*sth^2)), 0}, {0, 0}, {(3*Sqrt[2]*cth*gc38*sth*(cth*ctWIm - I*cth*ctWRe - ctBIm*sth + I*ctBRe*sth)*vevhat*IndexDelta[e1x2, e2x2])/(FCGV["EL"]*LambdaSMEFT^2*(-3 + 4*sth^2)), 0}, {0, 0}, {(3*Sqrt[2]*cth*gc38*sth*(cth*(ctWIm + I*ctWRe) - (ctBIm + I*ctBRe)*sth)*vevhat*IndexDelta[e1x2, e2x2])/(FCGV["EL"]*LambdaSMEFT^2*(-3 + 4*sth^2)), 0}, {0, 0}, {(-3*Sqrt[2]*cth*gc38*sth*(cth*ctWIm - I*cth*ctWRe - ctBIm*sth + I*ctBRe*sth)*vevhat*IndexDelta[e1x2, e2x2])/(FCGV["EL"]*LambdaSMEFT^2*(-3 + 4*sth^2)), 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[2] ] == {{I*gc39*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}, {((4*I)*gc39*sth^2*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3])/(-3 + 4*sth^2), 0}, {0, 0}, {(-3*Sqrt[2]*cth*gc39*sth*(cth*(cuWIm + I*cuWRe) - (cuBIm + I*cuBRe)*sth)*vevhat*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2])/(FCGV["EL"]*LambdaSMEFT^2*(-3 + 4*sth^2)), 0}, {0, 0}, {(3*Sqrt[2]*cth*gc39*sth*(cth*cuWIm - I*cth*cuWRe - cuBIm*sth + I*cuBRe*sth)*vevhat*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2])/(FCGV["EL"]*LambdaSMEFT^2*(-3 + 4*sth^2)), 0}, {0, 0}, {(3*Sqrt[2]*cth*gc39*sth*(cth*(cuWIm + I*cuWRe) - (cuBIm + I*cuBRe)*sth)*vevhat*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2])/(FCGV["EL"]*LambdaSMEFT^2*(-3 + 4*sth^2)), 0}, {0, 0}, {(-3*Sqrt[2]*cth*gc39*sth*(cth*cuWIm - I*cth*cuWRe - cuBIm*sth + I*cuBRe*sth)*vevhat*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2])/(FCGV["EL"]*LambdaSMEFT^2*(-3 + 4*sth^2)), 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[1, {e2x2}] , V[2] ] == {{I*gc40*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , -F[30, {e3x2}] , F[40, {e2x2}] , F[3, {e4x2, e4x3}] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {-(gc41[e1x2, e4x2]*(3*(cutbd8Im + I*cutbd8Re)*IndexDelta[e1x3, e4x3]*IndexDelta[e2x2, e3x2] + (6*cutbd1Im + (6*I)*cutbd1Re - cutbd8Im - I*cutbd8Re)*IndexDelta[e1x3, e2x2]*IndexDelta[e3x2, e4x3])), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[40, {e1x2}] , -F[40, {e3x2}] , F[40, {e2x2}] , F[40, {e4x2}] ] == {{I*gc42*IndexDelta[e1x2, e4x2]*IndexDelta[e2x2, e3x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc42*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[40, {e1x2}] , -F[4, {e3x2, e3x3}] , F[40, {e2x2}] , F[4, {e4x2, e4x3}] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc43*IndexDelta[e3x2, e4x2]*(3*cbd8*IndexDelta[e1x2, e4x3]*IndexDelta[e2x2, e3x3] + (6*cbd1 - cbd8)*IndexDelta[e1x2, e2x2]*IndexDelta[e3x3, e4x3]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , -F[4, {e3x2, e3x3}] , F[4, {e2x2, e2x3}] , F[4, {e4x2, e4x3}] ] == {{((I/2)*gc44*IndexDelta[e1x2, e4x2]*IndexDelta[e2x2, e3x2]*((6*cdd1 - cdd8)*IndexDelta[e1x3, e4x3]*IndexDelta[e2x3, e3x3] + 3*cdd8*IndexDelta[e1x3, e2x3]*IndexDelta[e3x3, e4x3]))/(3*cdd1 + cdd8), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {((I/2)*gc44*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2]*(3*cdd8*IndexDelta[e1x3, e4x3]*IndexDelta[e2x3, e3x3] + (6*cdd1 - cdd8)*IndexDelta[e1x3, e2x3]*IndexDelta[e3x3, e4x3]))/(3*cdd1 + cdd8), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[40, {e1x2}] , -F[2, {e3x2}] , F[40, {e2x2}] , F[2, {e4x2}] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc45*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , -F[2, {e3x2}] , F[4, {e2x2, e2x3}] , F[2, {e4x2}] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc46*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3]*IndexDelta[e3x2, e4x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2, {e1x2}] , -F[2, {e3x2}] , F[2, {e2x2}] , F[2, {e4x2}] ] == {{I*gc47*IndexDelta[e1x2, e4x2]*IndexDelta[e2x2, e3x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc47*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2, {e1x2}] , -F[30, {e3x2}] , F[2, {e2x2}] , F[30, {e4x2}] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc48*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[40, {e1x2}] , -F[30, {e3x2}] , F[40, {e2x2}] , F[30, {e4x2}] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc49*(3*ctb8*IndexDelta[e1x2, e4x2]*IndexDelta[e2x2, e3x2] + (6*ctb1 - ctb8)*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , -F[30, {e3x2}] , F[4, {e2x2, e2x3}] , F[30, {e4x2}] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {((I/2)*gc50*IndexDelta[e1x2, e2x2]*(3*ctd8*IndexDelta[e1x3, e4x2]*IndexDelta[e2x3, e3x2] + (6*ctd1 - ctd8)*IndexDelta[e1x3, e2x3]*IndexDelta[e3x2, e4x2]))/(3*ctd1 + ctd8), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[30, {e1x2}] , -F[30, {e3x2}] , F[30, {e2x2}] , F[30, {e4x2}] ] == {{I*gc51*IndexDelta[e1x2, e4x2]*IndexDelta[e2x2, e3x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc51*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2, {e1x2}] , -F[3, {e3x2, e3x3}] , F[2, {e2x2}] , F[3, {e4x2, e4x3}] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc52*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2]*IndexDelta[e3x3, e4x3], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[40, {e1x2}] , -F[3, {e3x2, e3x3}] , F[40, {e2x2}] , F[3, {e4x2, e4x3}] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc53*IndexDelta[e3x2, e4x2]*(3*cbu8*IndexDelta[e1x2, e4x3]*IndexDelta[e2x2, e3x3] + (6*cbu1 - cbu8)*IndexDelta[e1x2, e2x2]*IndexDelta[e3x3, e4x3]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[30, {e1x2}] , -F[3, {e3x2, e3x3}] , F[30, {e2x2}] , F[3, {e4x2, e4x3}] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc54*IndexDelta[e3x2, e4x2]*(3*ctu8*IndexDelta[e1x2, e4x3]*IndexDelta[e2x2, e3x3] + (6*ctu1 - ctu8)*IndexDelta[e1x2, e2x2]*IndexDelta[e3x3, e4x3]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , -F[3, {e3x2, e3x3}] , F[4, {e2x2, e2x3}] , F[3, {e4x2, e4x3}] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {((I/2)*gc55*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2]*(3*cud8*IndexDelta[e1x3, e4x3]*IndexDelta[e2x3, e3x3] + (6*cud1 - cud8)*IndexDelta[e1x3, e2x3]*IndexDelta[e3x3, e4x3]))/(3*cud1 + cud8), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , -F[3, {e3x2, e3x3}] , F[3, {e2x2, e2x3}] , F[3, {e4x2, e4x3}] ] == {{((I/2)*gc56*IndexDelta[e1x2, e4x2]*IndexDelta[e2x2, e3x2]*((6*cuu1 - cuu8)*IndexDelta[e1x3, e4x3]*IndexDelta[e2x3, e3x3] + 3*cuu8*IndexDelta[e1x3, e2x3]*IndexDelta[e3x3, e4x3]))/(3*cuu1 + cuu8), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {((I/2)*gc56*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2]*(3*cuu8*IndexDelta[e1x3, e4x3]*IndexDelta[e2x3, e3x3] + (6*cuu1 - cuu8)*IndexDelta[e1x3, e2x3]*IndexDelta[e3x3, e4x3]))/(3*cuu1 + cuu8), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[40, {e1x2}] , -F[3, {e3x2, e3x3}] , F[4, {e2x2, e2x3}] , F[30, {e4x2}] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {gc57[e3x2, e2x2]*(3*(cutbd8Im - I*cutbd8Re)*IndexDelta[e1x2, e4x2]*IndexDelta[e2x3, e3x3] + (6*cutbd1Im - (6*I)*cutbd1Re - cutbd8Im + I*cutbd8Re)*IndexDelta[e1x2, e2x3]*IndexDelta[e3x3, e4x2]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[40, {e1x2}] , F[40, {e2x2}] , S[1] , V[1] ] == {{gc58*(-(cbBIm*cth) - I*cbBRe*cth + (cbWIm + I*cbWRe)*sth)*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {gc58*(cbBIm*cth - I*cbBRe*cth - cbWIm*sth + I*cbWRe*sth)*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {gc58*(cbBIm*cth + I*cbBRe*cth - cbWIm*sth - I*cbWRe*sth)*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {gc58*(-(cbBIm*cth) + I*cbBRe*cth + (cbWIm - I*cbWRe)*sth)*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[40, {e1x2}] , F[40, {e2x2}] , S[1] , V[2] ] == {{-(gc59*(cbWIm*cth + I*cbWRe*cth + (cbBIm + I*cbBRe)*sth)*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {gc59*(cbWIm*cth - I*cbWRe*cth + (cbBIm - I*cbBRe)*sth)*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {gc59*(cbWIm*cth + I*cbWRe*cth + (cbBIm + I*cbBRe)*sth)*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-(gc59*(cbWIm*cth - I*cbWRe*cth + (cbBIm - I*cbBRe)*sth)*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[1] , V[1] ] == {{gc60*(ceBIm*cth + I*ceBRe*cth - ceWIm*sth - I*ceWRe*sth)*yl[e1x2, e2x2], 0}, {0, 0}, {gc60*(-(ceBIm*cth) + I*ceBRe*cth + (ceWIm - I*ceWRe)*sth)*yl[e2x2, e1x2], 0}, {0, 0}, {gc60*(-(ceBIm*cth) - I*ceBRe*cth + (ceWIm + I*ceWRe)*sth)*yl[e1x2, e2x2], 0}, {0, 0}, {gc60*(ceBIm*cth - I*ceBRe*cth - ceWIm*sth + I*ceWRe*sth)*yl[e2x2, e1x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[1] , V[2] ] == {{gc61*(ceWIm*cth + I*ceWRe*cth + (ceBIm + I*ceBRe)*sth)*yl[e1x2, e2x2], 0}, {0, 0}, {-(gc61*(ceWIm*cth - I*ceWRe*cth + (ceBIm - I*ceBRe)*sth)*yl[e2x2, e1x2]), 0}, {0, 0}, {-(gc61*(ceWIm*cth + I*ceWRe*cth + (ceBIm + I*ceBRe)*sth)*yl[e1x2, e2x2]), 0}, {0, 0}, {gc61*(ceWIm*cth - I*ceWRe*cth + (ceBIm - I*ceBRe)*sth)*yl[e2x2, e1x2], 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[30, {e2x2}] , S[1] , V[1] ] == {{-(gc62*(ctBIm*cth + I*ctBRe*cth + (ctWIm + I*ctWRe)*sth)*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {gc62*(ctBIm*cth - I*ctBRe*cth + (ctWIm - I*ctWRe)*sth)*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {gc62*(ctBIm*cth + I*ctBRe*cth + (ctWIm + I*ctWRe)*sth)*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-(gc62*(ctBIm*cth - I*ctBRe*cth + (ctWIm - I*ctWRe)*sth)*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[30, {e2x2}] , S[1] , V[2] ] == {{gc63*(cth*(ctWIm + I*ctWRe) - (ctBIm + I*ctBRe)*sth)*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {gc63*(-(cth*ctWIm) + I*cth*ctWRe + ctBIm*sth - I*ctBRe*sth)*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {gc63*(-(cth*(ctWIm + I*ctWRe)) + (ctBIm + I*ctBRe)*sth)*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {gc63*(cth*ctWIm - I*cth*ctWRe - ctBIm*sth + I*ctBRe*sth)*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[40, {e1x2}] , F[40, {e2x2}] , S[1] , V[4, {e3x2}] ] == {{-((cbGIm + I*cbGRe)*gc64*FASUNT[e3x2, e1x2, e2x2]), 0}, {0, 0}, {(cbGIm - I*cbGRe)*gc64*FASUNT[e3x2, e1x2, e2x2], 0}, {0, 0}, {(cbGIm + I*cbGRe)*gc64*FASUNT[e3x2, e1x2, e2x2], 0}, {0, 0}, {-((cbGIm - I*cbGRe)*gc64*FASUNT[e3x2, e1x2, e2x2]), 0}, {0, 0}},

C[ -F[40, {e1x2}] , F[40, {e2x2}] , S[1] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(cbGIm + I*cbGRe)*gc65*(FASUNT[e3x2, e4x2, e1x2, e2x2] - FASUNT[e4x2, e3x2, e1x2, e2x2]), 0}, {0, 0}, {-((cbGIm - I*cbGRe)*gc65*(FASUNT[e3x2, e4x2, e1x2, e2x2] - FASUNT[e4x2, e3x2, e1x2, e2x2])), 0}, {0, 0}, {-((cbGIm + I*cbGRe)*gc65*(FASUNT[e3x2, e4x2, e1x2, e2x2] - FASUNT[e4x2, e3x2, e1x2, e2x2])), 0}, {0, 0}, {(cbGIm - I*cbGRe)*gc65*(FASUNT[e3x2, e4x2, e1x2, e2x2] - FASUNT[e4x2, e3x2, e1x2, e2x2]), 0}, {0, 0}},

C[ -F[40, {e1x2}] , F[40, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(cbGIm + I*cbGRe)*gc66*(FASUNT[e3x2, e4x2, e1x2, e2x2] - FASUNT[e4x2, e3x2, e1x2, e2x2]), 0}, {0, 0}, {-((cbGIm - I*cbGRe)*gc66*(FASUNT[e3x2, e4x2, e1x2, e2x2] - FASUNT[e4x2, e3x2, e1x2, e2x2])), 0}, {0, 0}, {-((cbGIm + I*cbGRe)*gc66*(FASUNT[e3x2, e4x2, e1x2, e2x2] - FASUNT[e4x2, e3x2, e1x2, e2x2])), 0}, {0, 0}, {(cbGIm - I*cbGRe)*gc66*(FASUNT[e3x2, e4x2, e1x2, e2x2] - FASUNT[e4x2, e3x2, e1x2, e2x2]), 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[30, {e2x2}] , S[1] , V[4, {e3x2}] ] == {{-((ctGIm + I*ctGRe)*gc67*FASUNT[e3x2, e1x2, e2x2]), 0}, {0, 0}, {(ctGIm - I*ctGRe)*gc67*FASUNT[e3x2, e1x2, e2x2], 0}, {0, 0}, {(ctGIm + I*ctGRe)*gc67*FASUNT[e3x2, e1x2, e2x2], 0}, {0, 0}, {-((ctGIm - I*ctGRe)*gc67*FASUNT[e3x2, e1x2, e2x2]), 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[30, {e2x2}] , S[1] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(ctGIm + I*ctGRe)*gc68*(FASUNT[e3x2, e4x2, e1x2, e2x2] - FASUNT[e4x2, e3x2, e1x2, e2x2]), 0}, {0, 0}, {-((ctGIm - I*ctGRe)*gc68*(FASUNT[e3x2, e4x2, e1x2, e2x2] - FASUNT[e4x2, e3x2, e1x2, e2x2])), 0}, {0, 0}, {-((ctGIm + I*ctGRe)*gc68*(FASUNT[e3x2, e4x2, e1x2, e2x2] - FASUNT[e4x2, e3x2, e1x2, e2x2])), 0}, {0, 0}, {(ctGIm - I*ctGRe)*gc68*(FASUNT[e3x2, e4x2, e1x2, e2x2] - FASUNT[e4x2, e3x2, e1x2, e2x2]), 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[30, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(ctGIm + I*ctGRe)*gc69*(FASUNT[e3x2, e4x2, e1x2, e2x2] - FASUNT[e4x2, e3x2, e1x2, e2x2]), 0}, {0, 0}, {-((ctGIm - I*ctGRe)*gc69*(FASUNT[e3x2, e4x2, e1x2, e2x2] - FASUNT[e4x2, e3x2, e1x2, e2x2])), 0}, {0, 0}, {-((ctGIm + I*ctGRe)*gc69*(FASUNT[e3x2, e4x2, e1x2, e2x2] - FASUNT[e4x2, e3x2, e1x2, e2x2])), 0}, {0, 0}, {(ctGIm - I*ctGRe)*gc69*(FASUNT[e3x2, e4x2, e1x2, e2x2] - FASUNT[e4x2, e3x2, e1x2, e2x2]), 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] , V[1] ] == {{gc70*(cdBIm*cth + I*cdBRe*cth - cdWIm*sth - I*cdWRe*sth)*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2], 0}, {0, 0}, {gc70*(-(cdBIm*cth) + I*cdBRe*cth + (cdWIm - I*cdWRe)*sth)*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2], 0}, {0, 0}, {gc70*(-(cdBIm*cth) - I*cdBRe*cth + (cdWIm + I*cdWRe)*sth)*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2], 0}, {0, 0}, {gc70*(cdBIm*cth - I*cdBRe*cth - cdWIm*sth + I*cdWRe*sth)*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] , V[2] ] == {{gc71*(cdWIm*cth + I*cdWRe*cth + (cdBIm + I*cdBRe)*sth)*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2], 0}, {0, 0}, {-(gc71*(cdWIm*cth - I*cdWRe*cth + (cdBIm - I*cdBRe)*sth)*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2]), 0}, {0, 0}, {-(gc71*(cdWIm*cth + I*cdWRe*cth + (cdBIm + I*cdBRe)*sth)*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2]), 0}, {0, 0}, {gc71*(cdWIm*cth - I*cdWRe*cth + (cdBIm - I*cdBRe)*sth)*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] , V[4, {e3x2}] ] == {{(cdGIm + I*cdGRe)*gc72*FASUNT[e3x2, e1x3, e2x3]*ydtop[e1x2, e2x2], 0}, {0, 0}, {-((cdGIm - I*cdGRe)*gc72*FASUNT[e3x2, e1x3, e2x3]*ydtop[e2x2, e1x2]), 0}, {0, 0}, {-((cdGIm + I*cdGRe)*gc72*FASUNT[e3x2, e1x3, e2x3]*ydtop[e1x2, e2x2]), 0}, {0, 0}, {(cdGIm - I*cdGRe)*gc72*FASUNT[e3x2, e1x3, e2x3]*ydtop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{-((cdGIm + I*cdGRe)*gc73*(FASUNT[e3x2, e4x2, e1x3, e2x3] - FASUNT[e4x2, e3x2, e1x3, e2x3])*ydtop[e1x2, e2x2]), 0}, {0, 0}, {(cdGIm - I*cdGRe)*gc73*(FASUNT[e3x2, e4x2, e1x3, e2x3] - FASUNT[e4x2, e3x2, e1x3, e2x3])*ydtop[e2x2, e1x2], 0}, {0, 0}, {(cdGIm + I*cdGRe)*gc73*(FASUNT[e3x2, e4x2, e1x3, e2x3] - FASUNT[e4x2, e3x2, e1x3, e2x3])*ydtop[e1x2, e2x2], 0}, {0, 0}, {-((cdGIm - I*cdGRe)*gc73*(FASUNT[e3x2, e4x2, e1x3, e2x3] - FASUNT[e4x2, e3x2, e1x3, e2x3])*ydtop[e2x2, e1x2]), 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{-((cdGIm + I*cdGRe)*gc74*(FASUNT[e3x2, e4x2, e1x3, e2x3] - FASUNT[e4x2, e3x2, e1x3, e2x3])*ydtop[e1x2, e2x2]), 0}, {0, 0}, {(cdGIm - I*cdGRe)*gc74*(FASUNT[e3x2, e4x2, e1x3, e2x3] - FASUNT[e4x2, e3x2, e1x3, e2x3])*ydtop[e2x2, e1x2], 0}, {0, 0}, {(cdGIm + I*cdGRe)*gc74*(FASUNT[e3x2, e4x2, e1x3, e2x3] - FASUNT[e4x2, e3x2, e1x3, e2x3])*ydtop[e1x2, e2x2], 0}, {0, 0}, {-((cdGIm - I*cdGRe)*gc74*(FASUNT[e3x2, e4x2, e1x3, e2x3] - FASUNT[e4x2, e3x2, e1x3, e2x3])*ydtop[e2x2, e1x2]), 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] , V[1] ] == {{gc75*(cth*(cuBIm + I*cuBRe) + (cuWIm + I*cuWRe)*sth)*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2], 0}, {0, 0}, {-(gc75*(cth*(cuBIm - I*cuBRe) + (cuWIm - I*cuWRe)*sth)*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2]), 0}, {0, 0}, {-(gc75*(cth*(cuBIm + I*cuBRe) + (cuWIm + I*cuWRe)*sth)*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2]), 0}, {0, 0}, {gc75*(cth*(cuBIm - I*cuBRe) + (cuWIm - I*cuWRe)*sth)*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] , V[2] ] == {{gc76*(-(cth*(cuWIm + I*cuWRe)) + (cuBIm + I*cuBRe)*sth)*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2], 0}, {0, 0}, {gc76*(cth*cuWIm - I*cth*cuWRe - cuBIm*sth + I*cuBRe*sth)*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2], 0}, {0, 0}, {gc76*(cth*(cuWIm + I*cuWRe) - (cuBIm + I*cuBRe)*sth)*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2], 0}, {0, 0}, {gc76*(-(cth*cuWIm) + I*cth*cuWRe + cuBIm*sth - I*cuBRe*sth)*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] , V[4, {e3x2}] ] == {{(cuGIm + I*cuGRe)*gc77*FASUNT[e3x2, e1x3, e2x3]*yutop[e1x2, e2x2], 0}, {0, 0}, {-((cuGIm - I*cuGRe)*gc77*FASUNT[e3x2, e1x3, e2x3]*yutop[e2x2, e1x2]), 0}, {0, 0}, {-((cuGIm + I*cuGRe)*gc77*FASUNT[e3x2, e1x3, e2x3]*yutop[e1x2, e2x2]), 0}, {0, 0}, {(cuGIm - I*cuGRe)*gc77*FASUNT[e3x2, e1x3, e2x3]*yutop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{-((cuGIm + I*cuGRe)*gc78*(FASUNT[e3x2, e4x2, e1x3, e2x3] - FASUNT[e4x2, e3x2, e1x3, e2x3])*yutop[e1x2, e2x2]), 0}, {0, 0}, {(cuGIm - I*cuGRe)*gc78*(FASUNT[e3x2, e4x2, e1x3, e2x3] - FASUNT[e4x2, e3x2, e1x3, e2x3])*yutop[e2x2, e1x2], 0}, {0, 0}, {(cuGIm + I*cuGRe)*gc78*(FASUNT[e3x2, e4x2, e1x3, e2x3] - FASUNT[e4x2, e3x2, e1x3, e2x3])*yutop[e1x2, e2x2], 0}, {0, 0}, {-((cuGIm - I*cuGRe)*gc78*(FASUNT[e3x2, e4x2, e1x3, e2x3] - FASUNT[e4x2, e3x2, e1x3, e2x3])*yutop[e2x2, e1x2]), 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{-((cuGIm + I*cuGRe)*gc79*(FASUNT[e3x2, e4x2, e1x3, e2x3] - FASUNT[e4x2, e3x2, e1x3, e2x3])*yutop[e1x2, e2x2]), 0}, {0, 0}, {(cuGIm - I*cuGRe)*gc79*(FASUNT[e3x2, e4x2, e1x3, e2x3] - FASUNT[e4x2, e3x2, e1x3, e2x3])*yutop[e2x2, e1x2], 0}, {0, 0}, {(cuGIm + I*cuGRe)*gc79*(FASUNT[e3x2, e4x2, e1x3, e2x3] - FASUNT[e4x2, e3x2, e1x3, e2x3])*yutop[e1x2, e2x2], 0}, {0, 0}, {-((cuGIm - I*cuGRe)*gc79*(FASUNT[e3x2, e4x2, e1x3, e2x3] - FASUNT[e4x2, e3x2, e1x3, e2x3])*yutop[e2x2, e1x2]), 0}, {0, 0}},

C[ -F[40, {e1x2}] , F[30, {e2x2}] , S[1] , -V[3] ] == {{-((cbWIm + I*cbWRe)*gc80*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {(ctWIm - I*ctWRe)*gc80*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(cbWIm + I*cbWRe)*gc80*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-((ctWIm - I*ctWRe)*gc80*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[40, {e1x2}] , F[30, {e2x2}] , S[1] , V[1] , -V[3] ] == {{-((cbWIm + I*cbWRe)*gc81*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {(ctWIm - I*ctWRe)*gc81*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(cbWIm + I*cbWRe)*gc81*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-((ctWIm - I*ctWRe)*gc81*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[40, {e1x2}] , F[30, {e2x2}] , V[1] , -V[3] ] == {{-((cbWIm + I*cbWRe)*gc82*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {(ctWIm - I*ctWRe)*gc82*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(cbWIm + I*cbWRe)*gc82*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-((ctWIm - I*ctWRe)*gc82*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[40, {e1x2}] , F[40, {e2x2}] , S[1] , V[3] , -V[3] ] == {{-((cbWIm + I*cbWRe)*gc83*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {(cbWIm - I*cbWRe)*gc83*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(cbWIm + I*cbWRe)*gc83*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-((cbWIm - I*cbWRe)*gc83*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[40, {e1x2}] , F[40, {e2x2}] , V[3] , -V[3] ] == {{-((cbWIm + I*cbWRe)*gc84*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {(cbWIm - I*cbWRe)*gc84*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(cbWIm + I*cbWRe)*gc84*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-((cbWIm - I*cbWRe)*gc84*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[40, {e1x2}] , F[30, {e2x2}] , S[1] , -V[3] , V[2] ] == {{-((cbWIm + I*cbWRe)*gc85*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {(ctWIm - I*ctWRe)*gc85*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(cbWIm + I*cbWRe)*gc85*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-((ctWIm - I*ctWRe)*gc85*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[40, {e1x2}] , F[30, {e2x2}] , -V[3] , V[2] ] == {{-((cbWIm + I*cbWRe)*gc86*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {(ctWIm - I*ctWRe)*gc86*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(cbWIm + I*cbWRe)*gc86*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-((ctWIm - I*ctWRe)*gc86*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , S[1] , -V[3] ] == {{-(((ceWIm + I*ceWRe)*gc87[e1x2, e2x2])/(ceWIm + ceWRe)), 0}, {0, 0}, {0, 0}, {0, 0}, {((ceWIm + I*ceWRe)*gc87[e1x2, e2x2])/(ceWIm + ceWRe), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , S[1] , V[1] , -V[3] ] == {{-(((ceWIm + I*ceWRe)*gc88[e1x2, e2x2])/(ceWIm + ceWRe)), 0}, {0, 0}, {0, 0}, {0, 0}, {((ceWIm + I*ceWRe)*gc88[e1x2, e2x2])/(ceWIm + ceWRe), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , V[1] , -V[3] ] == {{-(((ceWIm + I*ceWRe)*gc89[e1x2, e2x2])/(ceWIm + ceWRe)), 0}, {0, 0}, {0, 0}, {0, 0}, {((ceWIm + I*ceWRe)*gc89[e1x2, e2x2])/(ceWIm + ceWRe), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[1] , V[3] , -V[3] ] == {{(ceWIm + I*ceWRe)*gc90*yl[e1x2, e2x2], 0}, {0, 0}, {-((ceWIm - I*ceWRe)*gc90*yl[e2x2, e1x2]), 0}, {0, 0}, {-((ceWIm + I*ceWRe)*gc90*yl[e1x2, e2x2]), 0}, {0, 0}, {(ceWIm - I*ceWRe)*gc90*yl[e2x2, e1x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[3] , -V[3] ] == {{(ceWIm + I*ceWRe)*gc91*yl[e1x2, e2x2], 0}, {0, 0}, {-((ceWIm - I*ceWRe)*gc91*yl[e2x2, e1x2]), 0}, {0, 0}, {-((ceWIm + I*ceWRe)*gc91*yl[e1x2, e2x2]), 0}, {0, 0}, {(ceWIm - I*ceWRe)*gc91*yl[e2x2, e1x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , S[1] , -V[3] , V[2] ] == {{-(((ceWIm + I*ceWRe)*gc92[e1x2, e2x2])/(ceWIm + ceWRe)), 0}, {0, 0}, {0, 0}, {0, 0}, {((ceWIm + I*ceWRe)*gc92[e1x2, e2x2])/(ceWIm + ceWRe), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -V[3] , V[2] ] == {{-(((ceWIm + I*ceWRe)*gc93[e1x2, e2x2])/(ceWIm + ceWRe)), 0}, {0, 0}, {0, 0}, {0, 0}, {((ceWIm + I*ceWRe)*gc93[e1x2, e2x2])/(ceWIm + ceWRe), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[40, {e2x2}] , S[1] , V[3] ] == {{-((ctWIm + I*ctWRe)*gc94*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {(cbWIm - I*cbWRe)*gc94*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(ctWIm + I*ctWRe)*gc94*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-((cbWIm - I*cbWRe)*gc94*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[40, {e2x2}] , S[1] , V[1] , V[3] ] == {{-((ctWIm + I*ctWRe)*gc95*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {(cbWIm - I*cbWRe)*gc95*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(ctWIm + I*ctWRe)*gc95*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-((cbWIm - I*cbWRe)*gc95*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[40, {e2x2}] , V[1] , V[3] ] == {{-((ctWIm + I*ctWRe)*gc96*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {(cbWIm - I*cbWRe)*gc96*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(ctWIm + I*ctWRe)*gc96*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-((cbWIm - I*cbWRe)*gc96*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[30, {e2x2}] , S[1] , V[3] , -V[3] ] == {{-((ctWIm + I*ctWRe)*gc97*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {(ctWIm - I*ctWRe)*gc97*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(ctWIm + I*ctWRe)*gc97*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-((ctWIm - I*ctWRe)*gc97*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[30, {e2x2}] , V[3] , -V[3] ] == {{-((ctWIm + I*ctWRe)*gc98*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {(ctWIm - I*ctWRe)*gc98*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(ctWIm + I*ctWRe)*gc98*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-((ctWIm - I*ctWRe)*gc98*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[40, {e2x2}] , S[1] , V[3] , V[2] ] == {{-((ctWIm + I*ctWRe)*gc99*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {(cbWIm - I*cbWRe)*gc99*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(ctWIm + I*ctWRe)*gc99*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-((cbWIm - I*cbWRe)*gc99*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[40, {e2x2}] , V[3] , V[2] ] == {{-((ctWIm + I*ctWRe)*gc100*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {(cbWIm - I*cbWRe)*gc100*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(ctWIm + I*ctWRe)*gc100*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-((cbWIm - I*cbWRe)*gc100*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] , -V[3] ] == {{(cdWIm + I*cdWRe)*gc101*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2], 0}, {0, 0}, {-((cuWIm - I*cuWRe)*gc101*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2]), 0}, {0, 0}, {-((cdWIm + I*cdWRe)*gc101*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2]), 0}, {0, 0}, {(cuWIm - I*cuWRe)*gc101*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] , V[1] , -V[3] ] == {{(cdWIm + I*cdWRe)*gc102*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2], 0}, {0, 0}, {-((cuWIm - I*cuWRe)*gc102*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2]), 0}, {0, 0}, {-((cdWIm + I*cdWRe)*gc102*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2]), 0}, {0, 0}, {(cuWIm - I*cuWRe)*gc102*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[1] , -V[3] ] == {{(cdWIm + I*cdWRe)*gc103*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2], 0}, {0, 0}, {-((cuWIm - I*cuWRe)*gc103*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2]), 0}, {0, 0}, {-((cdWIm + I*cdWRe)*gc103*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2]), 0}, {0, 0}, {(cuWIm - I*cuWRe)*gc103*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] , V[3] , -V[3] ] == {{(cdWIm + I*cdWRe)*gc104*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2], 0}, {0, 0}, {-((cdWIm - I*cdWRe)*gc104*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2]), 0}, {0, 0}, {-((cdWIm + I*cdWRe)*gc104*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2]), 0}, {0, 0}, {(cdWIm - I*cdWRe)*gc104*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[3] , -V[3] ] == {{(cdWIm + I*cdWRe)*gc105*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2], 0}, {0, 0}, {-((cdWIm - I*cdWRe)*gc105*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2]), 0}, {0, 0}, {-((cdWIm + I*cdWRe)*gc105*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2]), 0}, {0, 0}, {(cdWIm - I*cdWRe)*gc105*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] , -V[3] , V[2] ] == {{(cdWIm + I*cdWRe)*gc106*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2], 0}, {0, 0}, {-((cuWIm - I*cuWRe)*gc106*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2]), 0}, {0, 0}, {-((cdWIm + I*cdWRe)*gc106*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2]), 0}, {0, 0}, {(cuWIm - I*cuWRe)*gc106*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -V[3] , V[2] ] == {{(cdWIm + I*cdWRe)*gc107*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2], 0}, {0, 0}, {-((cuWIm - I*cuWRe)*gc107*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2]), 0}, {0, 0}, {-((cdWIm + I*cdWRe)*gc107*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2]), 0}, {0, 0}, {(cuWIm - I*cuWRe)*gc107*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] , V[3] ] == {{(cuWIm + I*cuWRe)*gc108*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2], 0}, {0, 0}, {-((cdWIm - I*cdWRe)*gc108*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2]), 0}, {0, 0}, {-((cuWIm + I*cuWRe)*gc108*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2]), 0}, {0, 0}, {(cdWIm - I*cdWRe)*gc108*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] , V[1] , V[3] ] == {{(cuWIm + I*cuWRe)*gc109*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2], 0}, {0, 0}, {-((cdWIm - I*cdWRe)*gc109*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2]), 0}, {0, 0}, {-((cuWIm + I*cuWRe)*gc109*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2]), 0}, {0, 0}, {(cdWIm - I*cdWRe)*gc109*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[1] , V[3] ] == {{(cuWIm + I*cuWRe)*gc110*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2], 0}, {0, 0}, {-((cdWIm - I*cdWRe)*gc110*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2]), 0}, {0, 0}, {-((cuWIm + I*cuWRe)*gc110*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2]), 0}, {0, 0}, {(cdWIm - I*cdWRe)*gc110*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] , V[3] , -V[3] ] == {{(cuWIm + I*cuWRe)*gc111*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2], 0}, {0, 0}, {-((cuWIm - I*cuWRe)*gc111*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2]), 0}, {0, 0}, {-((cuWIm + I*cuWRe)*gc111*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2]), 0}, {0, 0}, {(cuWIm - I*cuWRe)*gc111*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[3] , -V[3] ] == {{(cuWIm + I*cuWRe)*gc112*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2], 0}, {0, 0}, {-((cuWIm - I*cuWRe)*gc112*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2]), 0}, {0, 0}, {-((cuWIm + I*cuWRe)*gc112*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2]), 0}, {0, 0}, {(cuWIm - I*cuWRe)*gc112*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] , V[3] , V[2] ] == {{(cuWIm + I*cuWRe)*gc113*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2], 0}, {0, 0}, {-((cdWIm - I*cdWRe)*gc113*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2]), 0}, {0, 0}, {-((cuWIm + I*cuWRe)*gc113*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2]), 0}, {0, 0}, {(cdWIm - I*cdWRe)*gc113*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[3] , V[2] ] == {{(cuWIm + I*cuWRe)*gc114*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2], 0}, {0, 0}, {-((cdWIm - I*cdWRe)*gc114*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2]), 0}, {0, 0}, {-((cuWIm + I*cuWRe)*gc114*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2]), 0}, {0, 0}, {(cdWIm - I*cdWRe)*gc114*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , S[1] , V[3] ] == {{0, 0}, {0, 0}, {-(((ceWIm - I*ceWRe)*gc115[e1x2, e2x2])/(ceWIm - ceWRe)), 0}, {0, 0}, {0, 0}, {0, 0}, {((ceWIm - I*ceWRe)*gc115[e1x2, e2x2])/(ceWIm - ceWRe), 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , S[1] , V[1] , V[3] ] == {{0, 0}, {0, 0}, {-(((ceWIm - I*ceWRe)*gc116[e1x2, e2x2])/(ceWIm - ceWRe)), 0}, {0, 0}, {0, 0}, {0, 0}, {((ceWIm - I*ceWRe)*gc116[e1x2, e2x2])/(ceWIm - ceWRe), 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , V[1] , V[3] ] == {{0, 0}, {0, 0}, {((ceWIm - I*ceWRe)*gc117[e1x2, e2x2])/(-ceWIm + ceWRe), 0}, {0, 0}, {0, 0}, {0, 0}, {((ceWIm - I*ceWRe)*gc117[e1x2, e2x2])/(ceWIm - ceWRe), 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , S[1] , V[3] , V[2] ] == {{0, 0}, {0, 0}, {-(((ceWIm - I*ceWRe)*gc118[e1x2, e2x2])/(ceWIm - ceWRe)), 0}, {0, 0}, {0, 0}, {0, 0}, {((ceWIm - I*ceWRe)*gc118[e1x2, e2x2])/(ceWIm - ceWRe), 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , V[3] , V[2] ] == {{0, 0}, {0, 0}, {-(((ceWIm - I*ceWRe)*gc119[e1x2, e2x2])/(ceWIm - ceWRe)), 0}, {0, 0}, {0, 0}, {0, 0}, {((ceWIm - I*ceWRe)*gc119[e1x2, e2x2])/(ceWIm - ceWRe), 0}, {0, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc3 -> FAGS,
     gc4 -> -FAGS^2,
     gc5 -> FCGV["EL"]/3,
     gc6 -> FCGV["EL"]/3,
     gc7 -> FCGV["EL"],
     gc8 -> (-2*FCGV["EL"])/3,
     gc9 -> (-2*FCGV["EL"])/3,
     gc10 -> -(yb/Sqrt[2]),
     gc11 -> -(yt/Sqrt[2]),
     gc12 -> -FCGV["EL"],
     gc15 -> -FCGV["EL"]^2,
     gc16 -> -((cth*FCGV["EL"])/sth),
     gc17 -> FCGV["EL"]^2/sth^2,
     gc18[e1x2_, e2x2_] -> -(ydtop[e1x2, e2x2]/Sqrt[2]),
     gc19[e1x2_, e2x2_] -> -(yl[e1x2, e2x2]/Sqrt[2]),
     gc20[e1x2_, e2x2_] -> -(yutop[e1x2, e2x2]/Sqrt[2]),
     gc21 -> (cth*FCGV["EL"]^2)/sth,
     gc24 -> (FCGV["EL"]^2*(-1 + sth^2))/sth^2,
     gc25 -> -FAGS,
     gc26 -> -FAGS,
     gc27 -> -FAGS,
     gc28 -> -FAGS,
     gc29 -> -(FCGV["EL"]/(Sqrt[2]*sth)),
     gc30 -> -(FCGV["EL"]/(Sqrt[2]*sth)),
     gc31 -> -(FCGV["EL"]/(Sqrt[2]*sth)),
     gc32 -> -(FCGV["EL"]/(Sqrt[2]*sth)),
     gc33 -> -(FCGV["EL"]/(Sqrt[2]*sth)),
     gc34 -> -(FCGV["EL"]/(Sqrt[2]*sth)),
     gc35 -> -(FCGV["EL"]*(-3 + 2*sth^2))/(6*cth*sth),
     gc36 -> -(FCGV["EL"]*(-3 + 2*sth^2))/(6*cth*sth),
     gc37 -> -(FCGV["EL"]*(-1 + 2*sth^2))/(2*cth*sth),
     gc38 -> (FCGV["EL"]*(-3 + 4*sth^2))/(6*cth*sth),
     gc39 -> (FCGV["EL"]*(-3 + 4*sth^2))/(6*cth*sth),
     gc40 -> -FCGV["EL"]/(2*cth*sth),
     gc41[e1x2_, e4x2_] -> -IndexSum[ydtop[e1x2, Generation2$1]*yutop[e4x2, Generation2$1], {Generation2$1, 1, 2}]/(6*LambdaSMEFT^2),
     gc42 -> (2*cbb)/LambdaSMEFT^2,
     gc43 -> 1/(6*LambdaSMEFT^2),
     gc44 -> (2*(3*cdd1 + cdd8))/(3*LambdaSMEFT^2),
     gc45 -> cbe/LambdaSMEFT^2,
     gc46 -> ced/LambdaSMEFT^2,
     gc47 -> (2*cee)/LambdaSMEFT^2,
     gc48 -> cte/LambdaSMEFT^2,
     gc49 -> 1/(6*LambdaSMEFT^2),
     gc50 -> (6*ctd1 - ctd8)/(6*LambdaSMEFT^2) + ctd8/(2*LambdaSMEFT^2),
     gc51 -> (2*ctt)/LambdaSMEFT^2,
     gc52 -> ceu/LambdaSMEFT^2,
     gc53 -> 1/(6*LambdaSMEFT^2),
     gc54 -> 1/(6*LambdaSMEFT^2),
     gc55 -> (6*cud1 - cud8)/(6*LambdaSMEFT^2) + cud8/(2*LambdaSMEFT^2),
     gc56 -> (2*(3*cuu1 + cuu8))/(3*LambdaSMEFT^2),
     gc57[e3x2_, e2x2_] -> -IndexSum[ydtop[e2x2, Generation2$1]*yutop[e3x2, Generation2$1], {Generation2$1, 1, 2}]/(6*LambdaSMEFT^2),
     gc58 -> 1/(Sqrt[2]*LambdaSMEFT^2),
     gc59 -> -(1/(Sqrt[2]*LambdaSMEFT^2)),
     gc60 -> -(1/(Sqrt[2]*LambdaSMEFT^2)),
     gc61 -> 1/(Sqrt[2]*LambdaSMEFT^2),
     gc62 -> 1/(Sqrt[2]*LambdaSMEFT^2),
     gc63 -> -(1/(Sqrt[2]*LambdaSMEFT^2)),
     gc64 -> 1/(Sqrt[2]*LambdaSMEFT^2),
     gc65 -> -(FAGS/(Sqrt[2]*LambdaSMEFT^2)),
     gc66 -> -((FAGS*vevhat)/(Sqrt[2]*LambdaSMEFT^2)),
     gc67 -> 1/(Sqrt[2]*LambdaSMEFT^2),
     gc68 -> -(FAGS/(Sqrt[2]*LambdaSMEFT^2)),
     gc69 -> -((FAGS*vevhat)/(Sqrt[2]*LambdaSMEFT^2)),
     gc70 -> -(1/(Sqrt[2]*LambdaSMEFT^2)),
     gc71 -> 1/(Sqrt[2]*LambdaSMEFT^2),
     gc72 -> -(1/(Sqrt[2]*LambdaSMEFT^2)),
     gc73 -> FAGS/(Sqrt[2]*LambdaSMEFT^2),
     gc74 -> (FAGS*vevhat)/(Sqrt[2]*LambdaSMEFT^2),
     gc75 -> -(1/(Sqrt[2]*LambdaSMEFT^2)),
     gc76 -> 1/(Sqrt[2]*LambdaSMEFT^2),
     gc77 -> -(1/(Sqrt[2]*LambdaSMEFT^2)),
     gc78 -> FAGS/(Sqrt[2]*LambdaSMEFT^2),
     gc79 -> (FAGS*vevhat)/(Sqrt[2]*LambdaSMEFT^2),
     gc80 -> LambdaSMEFT^(-2),
     gc81 -> -(FCGV["EL"]/LambdaSMEFT^2),
     gc82 -> -((FCGV["EL"]*vevhat)/LambdaSMEFT^2),
     gc83 -> -(FCGV["EL"]/(Sqrt[2]*LambdaSMEFT^2*sth)),
     gc84 -> -((FCGV["EL"]*vevhat)/(Sqrt[2]*LambdaSMEFT^2*sth)),
     gc85 -> (cth*FCGV["EL"])/(LambdaSMEFT^2*sth),
     gc86 -> (cth*FCGV["EL"]*vevhat)/(LambdaSMEFT^2*sth),
     gc87[e1x2_, e2x2_] -> ((ceWIm + ceWRe)*yl[e1x2, e2x2])/LambdaSMEFT^2,
     gc88[e1x2_, e2x2_] -> -(((ceWIm + ceWRe)*FCGV["EL"]*yl[e1x2, e2x2])/LambdaSMEFT^2),
     gc89[e1x2_, e2x2_] -> -(((ceWIm + ceWRe)*FCGV["EL"]*vevhat*yl[e1x2, e2x2])/LambdaSMEFT^2),
     gc90 -> FCGV["EL"]/(Sqrt[2]*LambdaSMEFT^2*sth),
     gc91 -> (FCGV["EL"]*vevhat)/(Sqrt[2]*LambdaSMEFT^2*sth),
     gc92[e1x2_, e2x2_] -> ((ceWIm + ceWRe)*cth*FCGV["EL"]*yl[e1x2, e2x2])/(LambdaSMEFT^2*sth),
     gc93[e1x2_, e2x2_] -> ((ceWIm + ceWRe)*cth*FCGV["EL"]*vevhat*yl[e1x2, e2x2])/(LambdaSMEFT^2*sth),
     gc94 -> LambdaSMEFT^(-2),
     gc95 -> FCGV["EL"]/LambdaSMEFT^2,
     gc96 -> (FCGV["EL"]*vevhat)/LambdaSMEFT^2,
     gc97 -> FCGV["EL"]/(Sqrt[2]*LambdaSMEFT^2*sth),
     gc98 -> (FCGV["EL"]*vevhat)/(Sqrt[2]*LambdaSMEFT^2*sth),
     gc99 -> -((cth*FCGV["EL"])/(LambdaSMEFT^2*sth)),
     gc100 -> -((cth*FCGV["EL"]*vevhat)/(LambdaSMEFT^2*sth)),
     gc101 -> -LambdaSMEFT^(-2),
     gc102 -> FCGV["EL"]/LambdaSMEFT^2,
     gc103 -> (FCGV["EL"]*vevhat)/LambdaSMEFT^2,
     gc104 -> FCGV["EL"]/(Sqrt[2]*LambdaSMEFT^2*sth),
     gc105 -> (FCGV["EL"]*vevhat)/(Sqrt[2]*LambdaSMEFT^2*sth),
     gc106 -> -((cth*FCGV["EL"])/(LambdaSMEFT^2*sth)),
     gc107 -> -((cth*FCGV["EL"]*vevhat)/(LambdaSMEFT^2*sth)),
     gc108 -> -LambdaSMEFT^(-2),
     gc109 -> -(FCGV["EL"]/LambdaSMEFT^2),
     gc110 -> -((FCGV["EL"]*vevhat)/LambdaSMEFT^2),
     gc111 -> -(FCGV["EL"]/(Sqrt[2]*LambdaSMEFT^2*sth)),
     gc112 -> -((FCGV["EL"]*vevhat)/(Sqrt[2]*LambdaSMEFT^2*sth)),
     gc113 -> (cth*FCGV["EL"])/(LambdaSMEFT^2*sth),
     gc114 -> (cth*FCGV["EL"]*vevhat)/(LambdaSMEFT^2*sth),
     gc115[e1x2_, e2x2_] -> -(((ceWIm - ceWRe)*yl[e2x2, e1x2])/LambdaSMEFT^2),
     gc116[e1x2_, e2x2_] -> -(((ceWIm - ceWRe)*FCGV["EL"]*yl[e2x2, e1x2])/LambdaSMEFT^2),
     gc117[e1x2_, e2x2_] -> ((-ceWIm + ceWRe)*FCGV["EL"]*vevhat*yl[e2x2, e1x2])/LambdaSMEFT^2,
     gc118[e1x2_, e2x2_] -> ((ceWIm - ceWRe)*cth*FCGV["EL"]*yl[e2x2, e1x2])/(LambdaSMEFT^2*sth),
     gc119[e1x2_, e2x2_] -> ((ceWIm - ceWRe)*cth*FCGV["EL"]*vevhat*yl[e2x2, e1x2])/(LambdaSMEFT^2*sth)};

