(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"SMEFTsim",
  Authors -> {"I. Brivio"},
  Version -> "3.0.1",
  Date -> "January 2021",
  Institutions -> {"ITP, Universitat Heidelberg"},
  Emails -> {"brivio@thphys.uni-heidelberg.de"},
  References -> {"arXiv:1709.06492", "arXiv:2012.11343"},
  URLs -> {"https://feynrules.irmp.ucl.ac.be/wiki/SMEFT", "https://SMEFTsim.github.io"}};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}, {SMHLOOP, 0}, {NP, 0}, {NPshifts, 0}, {NPprop, 0}, {NPcpv, 0}, {NPcbb, 0}, {NPcbB, 0}, {NPcbBB, 0}, {NPcbd1, 0}, {NPcbd8, 0}, {NPcbe, 0}, {NPcbG, 0}, {NPcbH, 0}, {NPcbj1, 0}, {NPcbj8, 0}, {NPcbl, 0}, {NPcbu1, 0}, {NPcbu8, 0}, {NPcbW, 0}, {NPcdB, 0}, {NPcdd1, 0}, {NPcdd8, 0}, {NPcdG, 0}, {NPcdH, 0}, {NPcdW, 0}, {NPceB, 0}, {NPced, 0}, {NPcee, 0}, {NPceH, 0}, {NPceu, 0}, {NPceW, 0}, {NPcG, 0}, {NPcGtil, 0}, {NPcH, 0}, {NPcHB, 0}, {NPcHbox, 0}, {NPcHbq, 0}, {NPcHBtil, 0}, {NPcHd, 0}, {NPcHDD, 0}, {NPcHe, 0}, {NPcHG, 0}, {NPcHGtil, 0}, {NPcHj1, 0}, {NPcHj3, 0}, {NPcHl1, 0}, {NPcHl3, 0}, {NPcHQ1, 0}, {NPcHQ3, 0}, {NPcHt, 0}, {NPcHtb, 0}, {NPcHu, 0}, {NPcHud, 0}, {NPcHW, 0}, {NPcHWB, 0}, {NPcHWBtil, 0}, {NPcHWtil, 0}, {NPcjd1, 0}, {NPcjd8, 0}, {NPcje, 0}, {NPcjj11, 0}, {NPcjj18, 0}, {NPcjj31, 0}, {NPcjj38, 0}, {NPcjQbd1, 0}, {NPcjQbd8, 0}, {NPcjQtu1, 0}, {NPcjQtu8, 0}, {NPcjtQd1, 0}, {NPcjtQd8, 0}, {NPcju1, 0}, {NPcju8, 0}, {NPcjujd1, 0}, {NPcjujd11, 0}, {NPcjujd8, 0}, {NPcjujd81, 0}, {NPcjuQb1, 0}, {NPcjuQb8, 0}, {NPcld, 0}, {NPcle, 0}, {NPclebQ, 0}, {NPcledj, 0}, {NPcleju1, 0}, {NPcleju3, 0}, {NPcleQt1, 0}, {NPcleQt3, 0}, {NPclj1, 0}, {NPclj3, 0}, {NPcll, 0}, {NPcll1, 0}, {NPclu, 0}, {NPcQb1, 0}, {NPcQb8, 0}, {NPcQd1, 0}, {NPcQd8, 0}, {NPcQe, 0}, {NPcQj11, 0}, {NPcQj18, 0}, {NPcQj31, 0}, {NPcQj38, 0}, {NPcQl1, 0}, {NPcQl3, 0}, {NPcQQ1, 0}, {NPcQQ8, 0}, {NPcQt1, 0}, {NPcQt8, 0}, {NPcQtjd1, 0}, {NPcQtjd8, 0}, {NPcQtQb1, 0}, {NPcQtQb8, 0}, {NPcQu1, 0}, {NPcQu8, 0}, {NPcQujb1, 0}, {NPcQujb8, 0}, {NPctB, 0}, {NPctb1, 0}, {NPctb8, 0}, {NPctd1, 0}, {NPctd8, 0}, {NPcte, 0}, {NPctG, 0}, {NPctH, 0}, {NPctj1, 0}, {NPctj8, 0}, {NPctl, 0}, {NPctt, 0}, {NPctu1, 0}, {NPctu8, 0}, {NPctW, 0}, {NPcuB, 0}, {NPcud1, 0}, {NPcud8, 0}, {NPcuG, 0}, {NPcuH, 0}, {NPcutbd1, 0}, {NPcutbd8, 0}, {NPcuu1, 0}, {NPcuu8, 0}, {NPcuW, 0}, {NPcW, 0}, {NPcWtil, 0}, {NPQjujb8, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Generation2] ] = Range[ 2 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "a",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Z",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "W",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

V[4] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uA",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {} },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uZ",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {} },

U[31] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorLabel -> "uWp",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[32] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorLabel -> "uWm",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[4] == {
    SelfConjugate -> False,
    Indices -> {Index[Gluon]},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uG",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

V[13] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Superscript[Z,,]",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ1,
    Indices -> {} },

V[14] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "Superscript[W,,]",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW1,
    Indices -> {} },

F[1] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[2] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Ml },

F[3] == {
    Indices -> {Index[Generation2], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "uq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mu },

F[30] == {
    Indices -> {Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "t",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MT },

F[4] == {
    Indices -> {Index[Generation2], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorLabel -> "dq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Md },

F[40] == {
    Indices -> {Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorLabel -> "b",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MB },

F[31] == {
    Indices -> {Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "Superscript[t,,]",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MT1 },

S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "H",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {} },

S[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Go",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "GP",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {} },

S[4] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Superscript[H,,]",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH1,
    Indices -> {} }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[31] ] = GaugeXi[W];
GaugeXi[ U[32] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
MZ1[ ___ ] := MZ1;
MW1[ ___ ] := MW1;
Ml[ 1 ] := Me;
Ml[ 2 ] := MMU;
Ml[ 3 ] := MTA;
Mu[ 1, _ ] := MU;
Mu[ 1 ] := MU;
Mu[ 2, _ ] := MC;
Mu[ 2 ] := MC;
MT[ ___ ] := MT;
Md[ 1, _ ] := MD;
Md[ 1 ] := MD;
Md[ 2, _ ] := MS;
Md[ 2 ] := MS;
MB[ ___ ] := MB;
MT1[ ___ ] := MT1;
MH[ ___ ] := MH;
MH1[ ___ ] := MH1;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[4, {__}] ] := TheLabel[U[4]];
TheLabel[ F[1, {1}] ] := "ve";
TheLabel[ F[1, {2}] ] := "vm";
TheLabel[ F[1, {3}] ] := "vt";
TheLabel[ F[2, {1}] ] := "e";
TheLabel[ F[2, {2}] ] := "mu";
TheLabel[ F[2, {3}] ] := "ta";
TheLabel[ F[3, {1, _}] ] := "u";
TheLabel[ F[3, {1}] ] := "u";
TheLabel[ F[3, {2, _}] ] := "c";
TheLabel[ F[3, {2}] ] := "c";
TheLabel[ F[30, {__}] ] := TheLabel[F[30]];
TheLabel[ F[4, {1, _}] ] := "d";
TheLabel[ F[4, {1}] ] := "d";
TheLabel[ F[4, {2, _}] ] := "s";
TheLabel[ F[4, {2}] ] := "s";
TheLabel[ F[40, {__}] ] := TheLabel[F[40]];
TheLabel[ F[31, {__}] ] := TheLabel[F[31]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[1] , S[1] , S[1] , S[1] ] == {{((6*I)*lam*(-1 + sth)*(1 + sth))/cth^2, 0}},

C[ S[1] , S[1] , S[1] ] == {{((6*I)*lam*(-1 + sth)*(1 + sth)*vevhat)/cth^2, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc3*SUNF[e1x2, e2x2, e3x2]), 0}, {gc3*SUNF[e1x2, e2x2, e3x2], 0}, {gc3*SUNF[e1x2, e2x2, e3x2], 0}, {-(gc3*SUNF[e1x2, e2x2, e3x2]), 0}, {-(gc3*SUNF[e1x2, e2x2, e3x2]), 0}, {gc3*SUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc4*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc4*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc4*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ -F[40, {e1x2}] , F[40, {e2x2}] , V[1] ] == {{I*gc5*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {I*gc5*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(3*gc5*(-(cbBIm*cth) - I*cbBRe*cth + (cbWIm + I*cbWRe)*sth)*vevhat*IndexDelta[e1x2, e2x2])/(Sqrt[2]*EL*LambdaSMEFT^2), 0}, {0, 0}, {(3*gc5*(cbBIm*cth - I*cbBRe*cth - cbWIm*sth + I*cbWRe*sth)*vevhat*IndexDelta[e1x2, e2x2])/(Sqrt[2]*EL*LambdaSMEFT^2), 0}, {0, 0}, {(3*gc5*(cbBIm*cth + I*cbBRe*cth - cbWIm*sth - I*cbWRe*sth)*vevhat*IndexDelta[e1x2, e2x2])/(Sqrt[2]*EL*LambdaSMEFT^2), 0}, {0, 0}, {(3*gc5*(-(cbBIm*cth) + I*cbBRe*cth + (cbWIm - I*cbWRe)*sth)*vevhat*IndexDelta[e1x2, e2x2])/(Sqrt[2]*EL*LambdaSMEFT^2), 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[1] ] == {{I*gc6*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}, {I*gc6*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}, {(3*gc6*(-(cdBIm*cth) - I*cdBRe*cth + (cdWIm + I*cdWRe)*sth)*vevhat*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2])/(Sqrt[2]*EL*LambdaSMEFT^2), 0}, {0, 0}, {(3*gc6*(cdBIm*cth - I*cdBRe*cth - cdWIm*sth + I*cdWRe*sth)*vevhat*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2])/(Sqrt[2]*EL*LambdaSMEFT^2), 0}, {0, 0}, {(3*gc6*(cdBIm*cth + I*cdBRe*cth - cdWIm*sth - I*cdWRe*sth)*vevhat*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2])/(Sqrt[2]*EL*LambdaSMEFT^2), 0}, {0, 0}, {(3*gc6*(-(cdBIm*cth) + I*cdBRe*cth + (cdWIm - I*cdWRe)*sth)*vevhat*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2])/(Sqrt[2]*EL*LambdaSMEFT^2), 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[1] ] == {{I*gc7*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {I*gc7*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(gc7*(-(ceBIm*cth) - I*ceBRe*cth + (ceWIm + I*ceWRe)*sth)*vevhat*yl[e1x2, e2x2])/(Sqrt[2]*EL*LambdaSMEFT^2), 0}, {0, 0}, {(gc7*(ceBIm*cth - I*ceBRe*cth - ceWIm*sth + I*ceWRe*sth)*vevhat*yl[e2x2, e1x2])/(Sqrt[2]*EL*LambdaSMEFT^2), 0}, {0, 0}, {(gc7*(ceBIm*cth + I*ceBRe*cth - ceWIm*sth - I*ceWRe*sth)*vevhat*yl[e1x2, e2x2])/(Sqrt[2]*EL*LambdaSMEFT^2), 0}, {0, 0}, {(gc7*(-(ceBIm*cth) + I*ceBRe*cth + (ceWIm - I*ceWRe)*sth)*vevhat*yl[e2x2, e1x2])/(Sqrt[2]*EL*LambdaSMEFT^2), 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[30, {e2x2}] , V[1] ] == {{I*gc8*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {I*gc8*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(3*gc8*(ctBIm*cth + I*ctBRe*cth + (ctWIm + I*ctWRe)*sth)*vevhat*IndexDelta[e1x2, e2x2])/(2*Sqrt[2]*EL*LambdaSMEFT^2), 0}, {0, 0}, {(-3*gc8*(ctBIm*cth - I*ctBRe*cth + (ctWIm - I*ctWRe)*sth)*vevhat*IndexDelta[e1x2, e2x2])/(2*Sqrt[2]*EL*LambdaSMEFT^2), 0}, {0, 0}, {(-3*gc8*(ctBIm*cth + I*ctBRe*cth + (ctWIm + I*ctWRe)*sth)*vevhat*IndexDelta[e1x2, e2x2])/(2*Sqrt[2]*EL*LambdaSMEFT^2), 0}, {0, 0}, {(3*gc8*(ctBIm*cth - I*ctBRe*cth + (ctWIm - I*ctWRe)*sth)*vevhat*IndexDelta[e1x2, e2x2])/(2*Sqrt[2]*EL*LambdaSMEFT^2), 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[1] ] == {{I*gc9*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}, {I*gc9*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}, {(3*gc9*(cth*(cuBIm + I*cuBRe) + (cuWIm + I*cuWRe)*sth)*vevhat*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2])/(2*Sqrt[2]*EL*LambdaSMEFT^2), 0}, {0, 0}, {(-3*gc9*(cth*(cuBIm - I*cuBRe) + (cuWIm - I*cuWRe)*sth)*vevhat*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2])/(2*Sqrt[2]*EL*LambdaSMEFT^2), 0}, {0, 0}, {(-3*gc9*(cth*(cuBIm + I*cuBRe) + (cuWIm + I*cuWRe)*sth)*vevhat*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2])/(2*Sqrt[2]*EL*LambdaSMEFT^2), 0}, {0, 0}, {(3*gc9*(cth*(cuBIm - I*cuBRe) + (cuWIm - I*cuWRe)*sth)*vevhat*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2])/(2*Sqrt[2]*EL*LambdaSMEFT^2), 0}, {0, 0}},

C[ -F[40, {e1x2}] , F[40, {e2x2}] , S[1] ] == {{I*gc10*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {I*gc10*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[30, {e2x2}] , S[1] ] == {{I*gc11*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {I*gc11*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc12, 0}, {I*gc12, 0}, {I*gc12, 0}, {(-I)*gc12, 0}, {(-I)*gc12, 0}, {I*gc12, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((-I/2)*EL^2*(-1 + sth)*(1 + sth))/(cth^2*sth^2), 0}},

C[ S[1] , V[3] , -V[3] ] == {{((-I/2)*EL^2*(-1 + sth)*(1 + sth)*vevhat)/(cth^2*sth^2), 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc15, 0}, {(-I)*gc15, 0}, {(2*I)*gc15, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc16, 0}, {I*gc16, 0}, {I*gc16, 0}, {(-I)*gc16, 0}, {(-I)*gc16, 0}, {I*gc16, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc17, 0}, {(-I)*gc17, 0}, {(2*I)*gc17, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] ] == {{I*gc18[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}, {(I*gc18[e1x2, e2x2]*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2])/ydtop[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[1] ] == {{I*gc19[e1x2, e2x2], 0}, {0, 0}, {(I*gc19[e1x2, e2x2]*yl[e2x2, e1x2])/yl[e1x2, e2x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] ] == {{I*gc20[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}, {(I*gc20[e1x2, e2x2]*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2])/yutop[e1x2, e2x2], 0}, {0, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc21, 0}, {I*gc21, 0}, {I*gc21, 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*EL^2)/(cth^2*sth^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*vevhat)/(cth^2*sth^2), 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc24, 0}, {(-I)*gc24, 0}, {(2*I)*gc24, 0}},

C[ -F[40, {e1x2}] , F[40, {e2x2}] , V[4, {e3x2}] ] == {{I*gc25*SUNT[e3x2, e1x2, e2x2], 0}, {0, 0}, {I*gc25*SUNT[e3x2, e1x2, e2x2], 0}, {0, 0}, {((cbGIm + I*cbGRe)*gc25*vevhat*SUNT[e3x2, e1x2, e2x2])/(Sqrt[2]*GS*LambdaSMEFT^2), 0}, {0, 0}, {-(((cbGIm - I*cbGRe)*gc25*vevhat*SUNT[e3x2, e1x2, e2x2])/(Sqrt[2]*GS*LambdaSMEFT^2)), 0}, {0, 0}, {-(((cbGIm + I*cbGRe)*gc25*vevhat*SUNT[e3x2, e1x2, e2x2])/(Sqrt[2]*GS*LambdaSMEFT^2)), 0}, {0, 0}, {((cbGIm - I*cbGRe)*gc25*vevhat*SUNT[e3x2, e1x2, e2x2])/(Sqrt[2]*GS*LambdaSMEFT^2), 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc26*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {0, 0}, {I*gc26*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {0, 0}, {((cdGIm + I*cdGRe)*gc26*vevhat*SUNT[e3x2, e1x3, e2x3]*ydtop[e1x2, e2x2])/(Sqrt[2]*GS*LambdaSMEFT^2), 0}, {0, 0}, {-(((cdGIm - I*cdGRe)*gc26*vevhat*SUNT[e3x2, e1x3, e2x3]*ydtop[e2x2, e1x2])/(Sqrt[2]*GS*LambdaSMEFT^2)), 0}, {0, 0}, {-(((cdGIm + I*cdGRe)*gc26*vevhat*SUNT[e3x2, e1x3, e2x3]*ydtop[e1x2, e2x2])/(Sqrt[2]*GS*LambdaSMEFT^2)), 0}, {0, 0}, {((cdGIm - I*cdGRe)*gc26*vevhat*SUNT[e3x2, e1x3, e2x3]*ydtop[e2x2, e1x2])/(Sqrt[2]*GS*LambdaSMEFT^2), 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[30, {e2x2}] , V[4, {e3x2}] ] == {{I*gc27*SUNT[e3x2, e1x2, e2x2], 0}, {0, 0}, {I*gc27*SUNT[e3x2, e1x2, e2x2], 0}, {0, 0}, {((ctGIm + I*ctGRe)*gc27*vevhat*SUNT[e3x2, e1x2, e2x2])/(Sqrt[2]*GS*LambdaSMEFT^2), 0}, {0, 0}, {-(((ctGIm - I*ctGRe)*gc27*vevhat*SUNT[e3x2, e1x2, e2x2])/(Sqrt[2]*GS*LambdaSMEFT^2)), 0}, {0, 0}, {-(((ctGIm + I*ctGRe)*gc27*vevhat*SUNT[e3x2, e1x2, e2x2])/(Sqrt[2]*GS*LambdaSMEFT^2)), 0}, {0, 0}, {((ctGIm - I*ctGRe)*gc27*vevhat*SUNT[e3x2, e1x2, e2x2])/(Sqrt[2]*GS*LambdaSMEFT^2), 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc28*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {0, 0}, {I*gc28*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {0, 0}, {((cuGIm + I*cuGRe)*gc28*vevhat*SUNT[e3x2, e1x3, e2x3]*yutop[e1x2, e2x2])/(Sqrt[2]*GS*LambdaSMEFT^2), 0}, {0, 0}, {-(((cuGIm - I*cuGRe)*gc28*vevhat*SUNT[e3x2, e1x3, e2x3]*yutop[e2x2, e1x2])/(Sqrt[2]*GS*LambdaSMEFT^2)), 0}, {0, 0}, {-(((cuGIm + I*cuGRe)*gc28*vevhat*SUNT[e3x2, e1x3, e2x3]*yutop[e1x2, e2x2])/(Sqrt[2]*GS*LambdaSMEFT^2)), 0}, {0, 0}, {((cuGIm - I*cuGRe)*gc28*vevhat*SUNT[e3x2, e1x3, e2x3]*yutop[e2x2, e1x2])/(Sqrt[2]*GS*LambdaSMEFT^2), 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[40, {e2x2}] , V[3] ] == {{I*gc29*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {(Sqrt[2]*(ctWIm + I*ctWRe)*gc29*sth*vevhat*IndexDelta[e1x2, e2x2])/(EL*LambdaSMEFT^2), 0}, {0, 0}, {-((Sqrt[2]*(cbWIm - I*cbWRe)*gc29*sth*vevhat*IndexDelta[e1x2, e2x2])/(EL*LambdaSMEFT^2)), 0}, {0, 0}, {-((Sqrt[2]*(ctWIm + I*ctWRe)*gc29*sth*vevhat*IndexDelta[e1x2, e2x2])/(EL*LambdaSMEFT^2)), 0}, {0, 0}, {(Sqrt[2]*(cbWIm - I*cbWRe)*gc29*sth*vevhat*IndexDelta[e1x2, e2x2])/(EL*LambdaSMEFT^2), 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[3] ] == {{I*gc30*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}, {0, 0}, {0, 0}, {(Sqrt[2]*(cuWIm + I*cuWRe)*gc30*sth*vevhat*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2])/(EL*LambdaSMEFT^2), 0}, {0, 0}, {-((Sqrt[2]*(cdWIm - I*cdWRe)*gc30*sth*vevhat*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2])/(EL*LambdaSMEFT^2)), 0}, {0, 0}, {-((Sqrt[2]*(cuWIm + I*cuWRe)*gc30*sth*vevhat*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2])/(EL*LambdaSMEFT^2)), 0}, {0, 0}, {(Sqrt[2]*(cdWIm - I*cdWRe)*gc30*sth*vevhat*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2])/(EL*LambdaSMEFT^2), 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , V[3] ] == {{I*gc31*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {-((Sqrt[2]*(ceWIm - I*ceWRe)*gc31*sth*vevhat*yl[e2x2, e1x2])/(EL*LambdaSMEFT^2)), 0}, {0, 0}, {0, 0}, {0, 0}, {(Sqrt[2]*(ceWIm - I*ceWRe)*gc31*sth*vevhat*yl[e2x2, e1x2])/(EL*LambdaSMEFT^2), 0}, {0, 0}},

C[ -F[40, {e1x2}] , F[30, {e2x2}] , -V[3] ] == {{I*gc32*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {(Sqrt[2]*(cbWIm + I*cbWRe)*gc32*sth*vevhat*IndexDelta[e1x2, e2x2])/(EL*LambdaSMEFT^2), 0}, {0, 0}, {-((Sqrt[2]*(ctWIm - I*ctWRe)*gc32*sth*vevhat*IndexDelta[e1x2, e2x2])/(EL*LambdaSMEFT^2)), 0}, {0, 0}, {-((Sqrt[2]*(cbWIm + I*cbWRe)*gc32*sth*vevhat*IndexDelta[e1x2, e2x2])/(EL*LambdaSMEFT^2)), 0}, {0, 0}, {(Sqrt[2]*(ctWIm - I*ctWRe)*gc32*sth*vevhat*IndexDelta[e1x2, e2x2])/(EL*LambdaSMEFT^2), 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -V[3] ] == {{I*gc33*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}, {0, 0}, {0, 0}, {(Sqrt[2]*(cdWIm + I*cdWRe)*gc33*sth*vevhat*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2])/(EL*LambdaSMEFT^2), 0}, {0, 0}, {-((Sqrt[2]*(cuWIm - I*cuWRe)*gc33*sth*vevhat*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2])/(EL*LambdaSMEFT^2)), 0}, {0, 0}, {-((Sqrt[2]*(cdWIm + I*cdWRe)*gc33*sth*vevhat*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2])/(EL*LambdaSMEFT^2)), 0}, {0, 0}, {(Sqrt[2]*(cuWIm - I*cuWRe)*gc33*sth*vevhat*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2])/(EL*LambdaSMEFT^2), 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -V[3] ] == {{I*gc34*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {(Sqrt[2]*(ceWIm + I*ceWRe)*gc34*sth*vevhat*yl[e1x2, e2x2])/(EL*LambdaSMEFT^2), 0}, {0, 0}, {0, 0}, {0, 0}, {-((Sqrt[2]*(ceWIm + I*ceWRe)*gc34*sth*vevhat*yl[e1x2, e2x2])/(EL*LambdaSMEFT^2)), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[40, {e1x2}] , F[40, {e2x2}] , V[2] ] == {{I*gc35*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {((2*I)*gc35*sth^2*IndexDelta[e1x2, e2x2])/(-3 + 2*sth^2), 0}, {0, 0}, {(-3*Sqrt[2]*cth*gc35*sth*(cbWIm*cth + I*cbWRe*cth + (cbBIm + I*cbBRe)*sth)*vevhat*IndexDelta[e1x2, e2x2])/(EL*LambdaSMEFT^2*(-3 + 2*sth^2)), 0}, {0, 0}, {(3*Sqrt[2]*cth*gc35*sth*(cbWIm*cth - I*cbWRe*cth + (cbBIm - I*cbBRe)*sth)*vevhat*IndexDelta[e1x2, e2x2])/(EL*LambdaSMEFT^2*(-3 + 2*sth^2)), 0}, {0, 0}, {(3*Sqrt[2]*cth*gc35*sth*(cbWIm*cth + I*cbWRe*cth + (cbBIm + I*cbBRe)*sth)*vevhat*IndexDelta[e1x2, e2x2])/(EL*LambdaSMEFT^2*(-3 + 2*sth^2)), 0}, {0, 0}, {(-3*Sqrt[2]*cth*gc35*sth*(cbWIm*cth - I*cbWRe*cth + (cbBIm - I*cbBRe)*sth)*vevhat*IndexDelta[e1x2, e2x2])/(EL*LambdaSMEFT^2*(-3 + 2*sth^2)), 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[2] ] == {{I*gc36*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}, {((2*I)*gc36*sth^2*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3])/(-3 + 2*sth^2), 0}, {0, 0}, {(-3*Sqrt[2]*cth*gc36*sth*(cdWIm*cth + I*cdWRe*cth + (cdBIm + I*cdBRe)*sth)*vevhat*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2])/(EL*LambdaSMEFT^2*(-3 + 2*sth^2)), 0}, {0, 0}, {(3*Sqrt[2]*cth*gc36*sth*(cdWIm*cth - I*cdWRe*cth + (cdBIm - I*cdBRe)*sth)*vevhat*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2])/(EL*LambdaSMEFT^2*(-3 + 2*sth^2)), 0}, {0, 0}, {(3*Sqrt[2]*cth*gc36*sth*(cdWIm*cth + I*cdWRe*cth + (cdBIm + I*cdBRe)*sth)*vevhat*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2])/(EL*LambdaSMEFT^2*(-3 + 2*sth^2)), 0}, {0, 0}, {(-3*Sqrt[2]*cth*gc36*sth*(cdWIm*cth - I*cdWRe*cth + (cdBIm - I*cdBRe)*sth)*vevhat*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2])/(EL*LambdaSMEFT^2*(-3 + 2*sth^2)), 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[2] ] == {{I*gc37*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {((2*I)*gc37*sth^2*IndexDelta[e1x2, e2x2])/(-1 + 2*sth^2), 0}, {0, 0}, {-((Sqrt[2]*cth*gc37*sth*(ceWIm*cth + I*ceWRe*cth + (ceBIm + I*ceBRe)*sth)*vevhat*yl[e1x2, e2x2])/(EL*LambdaSMEFT^2*(-1 + 2*sth^2))), 0}, {0, 0}, {(Sqrt[2]*cth*gc37*sth*(ceWIm*cth - I*ceWRe*cth + (ceBIm - I*ceBRe)*sth)*vevhat*yl[e2x2, e1x2])/(EL*LambdaSMEFT^2*(-1 + 2*sth^2)), 0}, {0, 0}, {(Sqrt[2]*cth*gc37*sth*(ceWIm*cth + I*ceWRe*cth + (ceBIm + I*ceBRe)*sth)*vevhat*yl[e1x2, e2x2])/(EL*LambdaSMEFT^2*(-1 + 2*sth^2)), 0}, {0, 0}, {-((Sqrt[2]*cth*gc37*sth*(ceWIm*cth - I*ceWRe*cth + (ceBIm - I*ceBRe)*sth)*vevhat*yl[e2x2, e1x2])/(EL*LambdaSMEFT^2*(-1 + 2*sth^2))), 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[30, {e2x2}] , V[2] ] == {{I*gc38*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {((4*I)*gc38*sth^2*IndexDelta[e1x2, e2x2])/(-3 + 4*sth^2), 0}, {0, 0}, {(-3*Sqrt[2]*cth*gc38*sth*(cth*(ctWIm + I*ctWRe) - (ctBIm + I*ctBRe)*sth)*vevhat*IndexDelta[e1x2, e2x2])/(EL*LambdaSMEFT^2*(-3 + 4*sth^2)), 0}, {0, 0}, {(3*Sqrt[2]*cth*gc38*sth*(cth*ctWIm - I*cth*ctWRe - ctBIm*sth + I*ctBRe*sth)*vevhat*IndexDelta[e1x2, e2x2])/(EL*LambdaSMEFT^2*(-3 + 4*sth^2)), 0}, {0, 0}, {(3*Sqrt[2]*cth*gc38*sth*(cth*(ctWIm + I*ctWRe) - (ctBIm + I*ctBRe)*sth)*vevhat*IndexDelta[e1x2, e2x2])/(EL*LambdaSMEFT^2*(-3 + 4*sth^2)), 0}, {0, 0}, {(-3*Sqrt[2]*cth*gc38*sth*(cth*ctWIm - I*cth*ctWRe - ctBIm*sth + I*ctBRe*sth)*vevhat*IndexDelta[e1x2, e2x2])/(EL*LambdaSMEFT^2*(-3 + 4*sth^2)), 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[2] ] == {{I*gc39*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}, {((4*I)*gc39*sth^2*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3])/(-3 + 4*sth^2), 0}, {0, 0}, {(-3*Sqrt[2]*cth*gc39*sth*(cth*(cuWIm + I*cuWRe) - (cuBIm + I*cuBRe)*sth)*vevhat*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2])/(EL*LambdaSMEFT^2*(-3 + 4*sth^2)), 0}, {0, 0}, {(3*Sqrt[2]*cth*gc39*sth*(cth*cuWIm - I*cth*cuWRe - cuBIm*sth + I*cuBRe*sth)*vevhat*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2])/(EL*LambdaSMEFT^2*(-3 + 4*sth^2)), 0}, {0, 0}, {(3*Sqrt[2]*cth*gc39*sth*(cth*(cuWIm + I*cuWRe) - (cuBIm + I*cuBRe)*sth)*vevhat*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2])/(EL*LambdaSMEFT^2*(-3 + 4*sth^2)), 0}, {0, 0}, {(-3*Sqrt[2]*cth*gc39*sth*(cth*cuWIm - I*cth*cuWRe - cuBIm*sth + I*cuBRe*sth)*vevhat*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2])/(EL*LambdaSMEFT^2*(-3 + 4*sth^2)), 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[1, {e2x2}] , V[2] ] == {{I*gc40*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[40, {e1x2}] , F[40, {e2x2}] , S[1] , V[1] ] == {{gc41*(-(cbBIm*cth) - I*cbBRe*cth + (cbWIm + I*cbWRe)*sth)*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {gc41*(cbBIm*cth - I*cbBRe*cth - cbWIm*sth + I*cbWRe*sth)*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {gc41*(cbBIm*cth + I*cbBRe*cth - cbWIm*sth - I*cbWRe*sth)*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {gc41*(-(cbBIm*cth) + I*cbBRe*cth + (cbWIm - I*cbWRe)*sth)*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[40, {e1x2}] , F[40, {e2x2}] , S[1] , V[2] ] == {{-(gc42*(cbWIm*cth + I*cbWRe*cth + (cbBIm + I*cbBRe)*sth)*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {gc42*(cbWIm*cth - I*cbWRe*cth + (cbBIm - I*cbBRe)*sth)*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {gc42*(cbWIm*cth + I*cbWRe*cth + (cbBIm + I*cbBRe)*sth)*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-(gc42*(cbWIm*cth - I*cbWRe*cth + (cbBIm - I*cbBRe)*sth)*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[1] , V[1] ] == {{gc43*(ceBIm*cth + I*ceBRe*cth - ceWIm*sth - I*ceWRe*sth)*yl[e1x2, e2x2], 0}, {0, 0}, {gc43*(-(ceBIm*cth) + I*ceBRe*cth + (ceWIm - I*ceWRe)*sth)*yl[e2x2, e1x2], 0}, {0, 0}, {gc43*(-(ceBIm*cth) - I*ceBRe*cth + (ceWIm + I*ceWRe)*sth)*yl[e1x2, e2x2], 0}, {0, 0}, {gc43*(ceBIm*cth - I*ceBRe*cth - ceWIm*sth + I*ceWRe*sth)*yl[e2x2, e1x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[1] , V[2] ] == {{gc44*(ceWIm*cth + I*ceWRe*cth + (ceBIm + I*ceBRe)*sth)*yl[e1x2, e2x2], 0}, {0, 0}, {-(gc44*(ceWIm*cth - I*ceWRe*cth + (ceBIm - I*ceBRe)*sth)*yl[e2x2, e1x2]), 0}, {0, 0}, {-(gc44*(ceWIm*cth + I*ceWRe*cth + (ceBIm + I*ceBRe)*sth)*yl[e1x2, e2x2]), 0}, {0, 0}, {gc44*(ceWIm*cth - I*ceWRe*cth + (ceBIm - I*ceBRe)*sth)*yl[e2x2, e1x2], 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[30, {e2x2}] , S[1] , V[1] ] == {{-(gc45*(ctBIm*cth + I*ctBRe*cth + (ctWIm + I*ctWRe)*sth)*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {gc45*(ctBIm*cth - I*ctBRe*cth + (ctWIm - I*ctWRe)*sth)*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {gc45*(ctBIm*cth + I*ctBRe*cth + (ctWIm + I*ctWRe)*sth)*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-(gc45*(ctBIm*cth - I*ctBRe*cth + (ctWIm - I*ctWRe)*sth)*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[30, {e2x2}] , S[1] , V[2] ] == {{gc46*(cth*(ctWIm + I*ctWRe) - (ctBIm + I*ctBRe)*sth)*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {gc46*(-(cth*ctWIm) + I*cth*ctWRe + ctBIm*sth - I*ctBRe*sth)*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {gc46*(-(cth*(ctWIm + I*ctWRe)) + (ctBIm + I*ctBRe)*sth)*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {gc46*(cth*ctWIm - I*cth*ctWRe - ctBIm*sth + I*ctBRe*sth)*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[40, {e1x2}] , F[40, {e2x2}] , S[1] , V[4, {e3x2}] ] == {{-((cbGIm + I*cbGRe)*gc47*SUNT[e3x2, e1x2, e2x2]), 0}, {0, 0}, {(cbGIm - I*cbGRe)*gc47*SUNT[e3x2, e1x2, e2x2], 0}, {0, 0}, {(cbGIm + I*cbGRe)*gc47*SUNT[e3x2, e1x2, e2x2], 0}, {0, 0}, {-((cbGIm - I*cbGRe)*gc47*SUNT[e3x2, e1x2, e2x2]), 0}, {0, 0}},

C[ -F[40, {e1x2}] , F[40, {e2x2}] , S[1] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(cbGIm + I*cbGRe)*gc48*(SUNT[e3x2, e4x2, e1x2, e2x2] - SUNT[e4x2, e3x2, e1x2, e2x2]), 0}, {0, 0}, {-((cbGIm - I*cbGRe)*gc48*(SUNT[e3x2, e4x2, e1x2, e2x2] - SUNT[e4x2, e3x2, e1x2, e2x2])), 0}, {0, 0}, {-((cbGIm + I*cbGRe)*gc48*(SUNT[e3x2, e4x2, e1x2, e2x2] - SUNT[e4x2, e3x2, e1x2, e2x2])), 0}, {0, 0}, {(cbGIm - I*cbGRe)*gc48*(SUNT[e3x2, e4x2, e1x2, e2x2] - SUNT[e4x2, e3x2, e1x2, e2x2]), 0}, {0, 0}},

C[ -F[40, {e1x2}] , F[40, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(cbGIm + I*cbGRe)*gc49*(SUNT[e3x2, e4x2, e1x2, e2x2] - SUNT[e4x2, e3x2, e1x2, e2x2]), 0}, {0, 0}, {-((cbGIm - I*cbGRe)*gc49*(SUNT[e3x2, e4x2, e1x2, e2x2] - SUNT[e4x2, e3x2, e1x2, e2x2])), 0}, {0, 0}, {-((cbGIm + I*cbGRe)*gc49*(SUNT[e3x2, e4x2, e1x2, e2x2] - SUNT[e4x2, e3x2, e1x2, e2x2])), 0}, {0, 0}, {(cbGIm - I*cbGRe)*gc49*(SUNT[e3x2, e4x2, e1x2, e2x2] - SUNT[e4x2, e3x2, e1x2, e2x2]), 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[30, {e2x2}] , S[1] , V[4, {e3x2}] ] == {{-((ctGIm + I*ctGRe)*gc50*SUNT[e3x2, e1x2, e2x2]), 0}, {0, 0}, {(ctGIm - I*ctGRe)*gc50*SUNT[e3x2, e1x2, e2x2], 0}, {0, 0}, {(ctGIm + I*ctGRe)*gc50*SUNT[e3x2, e1x2, e2x2], 0}, {0, 0}, {-((ctGIm - I*ctGRe)*gc50*SUNT[e3x2, e1x2, e2x2]), 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[30, {e2x2}] , S[1] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(ctGIm + I*ctGRe)*gc51*(SUNT[e3x2, e4x2, e1x2, e2x2] - SUNT[e4x2, e3x2, e1x2, e2x2]), 0}, {0, 0}, {-((ctGIm - I*ctGRe)*gc51*(SUNT[e3x2, e4x2, e1x2, e2x2] - SUNT[e4x2, e3x2, e1x2, e2x2])), 0}, {0, 0}, {-((ctGIm + I*ctGRe)*gc51*(SUNT[e3x2, e4x2, e1x2, e2x2] - SUNT[e4x2, e3x2, e1x2, e2x2])), 0}, {0, 0}, {(ctGIm - I*ctGRe)*gc51*(SUNT[e3x2, e4x2, e1x2, e2x2] - SUNT[e4x2, e3x2, e1x2, e2x2]), 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[30, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(ctGIm + I*ctGRe)*gc52*(SUNT[e3x2, e4x2, e1x2, e2x2] - SUNT[e4x2, e3x2, e1x2, e2x2]), 0}, {0, 0}, {-((ctGIm - I*ctGRe)*gc52*(SUNT[e3x2, e4x2, e1x2, e2x2] - SUNT[e4x2, e3x2, e1x2, e2x2])), 0}, {0, 0}, {-((ctGIm + I*ctGRe)*gc52*(SUNT[e3x2, e4x2, e1x2, e2x2] - SUNT[e4x2, e3x2, e1x2, e2x2])), 0}, {0, 0}, {(ctGIm - I*ctGRe)*gc52*(SUNT[e3x2, e4x2, e1x2, e2x2] - SUNT[e4x2, e3x2, e1x2, e2x2]), 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] , V[1] ] == {{gc53*(cdBIm*cth + I*cdBRe*cth - cdWIm*sth - I*cdWRe*sth)*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2], 0}, {0, 0}, {gc53*(-(cdBIm*cth) + I*cdBRe*cth + (cdWIm - I*cdWRe)*sth)*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2], 0}, {0, 0}, {gc53*(-(cdBIm*cth) - I*cdBRe*cth + (cdWIm + I*cdWRe)*sth)*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2], 0}, {0, 0}, {gc53*(cdBIm*cth - I*cdBRe*cth - cdWIm*sth + I*cdWRe*sth)*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] , V[2] ] == {{gc54*(cdWIm*cth + I*cdWRe*cth + (cdBIm + I*cdBRe)*sth)*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2], 0}, {0, 0}, {-(gc54*(cdWIm*cth - I*cdWRe*cth + (cdBIm - I*cdBRe)*sth)*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2]), 0}, {0, 0}, {-(gc54*(cdWIm*cth + I*cdWRe*cth + (cdBIm + I*cdBRe)*sth)*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2]), 0}, {0, 0}, {gc54*(cdWIm*cth - I*cdWRe*cth + (cdBIm - I*cdBRe)*sth)*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] , V[4, {e3x2}] ] == {{(cdGIm + I*cdGRe)*gc55*SUNT[e3x2, e1x3, e2x3]*ydtop[e1x2, e2x2], 0}, {0, 0}, {-((cdGIm - I*cdGRe)*gc55*SUNT[e3x2, e1x3, e2x3]*ydtop[e2x2, e1x2]), 0}, {0, 0}, {-((cdGIm + I*cdGRe)*gc55*SUNT[e3x2, e1x3, e2x3]*ydtop[e1x2, e2x2]), 0}, {0, 0}, {(cdGIm - I*cdGRe)*gc55*SUNT[e3x2, e1x3, e2x3]*ydtop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{-((cdGIm + I*cdGRe)*gc56*(SUNT[e3x2, e4x2, e1x3, e2x3] - SUNT[e4x2, e3x2, e1x3, e2x3])*ydtop[e1x2, e2x2]), 0}, {0, 0}, {(cdGIm - I*cdGRe)*gc56*(SUNT[e3x2, e4x2, e1x3, e2x3] - SUNT[e4x2, e3x2, e1x3, e2x3])*ydtop[e2x2, e1x2], 0}, {0, 0}, {(cdGIm + I*cdGRe)*gc56*(SUNT[e3x2, e4x2, e1x3, e2x3] - SUNT[e4x2, e3x2, e1x3, e2x3])*ydtop[e1x2, e2x2], 0}, {0, 0}, {-((cdGIm - I*cdGRe)*gc56*(SUNT[e3x2, e4x2, e1x3, e2x3] - SUNT[e4x2, e3x2, e1x3, e2x3])*ydtop[e2x2, e1x2]), 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{-((cdGIm + I*cdGRe)*gc57*(SUNT[e3x2, e4x2, e1x3, e2x3] - SUNT[e4x2, e3x2, e1x3, e2x3])*ydtop[e1x2, e2x2]), 0}, {0, 0}, {(cdGIm - I*cdGRe)*gc57*(SUNT[e3x2, e4x2, e1x3, e2x3] - SUNT[e4x2, e3x2, e1x3, e2x3])*ydtop[e2x2, e1x2], 0}, {0, 0}, {(cdGIm + I*cdGRe)*gc57*(SUNT[e3x2, e4x2, e1x3, e2x3] - SUNT[e4x2, e3x2, e1x3, e2x3])*ydtop[e1x2, e2x2], 0}, {0, 0}, {-((cdGIm - I*cdGRe)*gc57*(SUNT[e3x2, e4x2, e1x3, e2x3] - SUNT[e4x2, e3x2, e1x3, e2x3])*ydtop[e2x2, e1x2]), 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] , V[1] ] == {{gc58*(cth*(cuBIm + I*cuBRe) + (cuWIm + I*cuWRe)*sth)*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2], 0}, {0, 0}, {-(gc58*(cth*(cuBIm - I*cuBRe) + (cuWIm - I*cuWRe)*sth)*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2]), 0}, {0, 0}, {-(gc58*(cth*(cuBIm + I*cuBRe) + (cuWIm + I*cuWRe)*sth)*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2]), 0}, {0, 0}, {gc58*(cth*(cuBIm - I*cuBRe) + (cuWIm - I*cuWRe)*sth)*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] , V[2] ] == {{gc59*(-(cth*(cuWIm + I*cuWRe)) + (cuBIm + I*cuBRe)*sth)*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2], 0}, {0, 0}, {gc59*(cth*cuWIm - I*cth*cuWRe - cuBIm*sth + I*cuBRe*sth)*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2], 0}, {0, 0}, {gc59*(cth*(cuWIm + I*cuWRe) - (cuBIm + I*cuBRe)*sth)*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2], 0}, {0, 0}, {gc59*(-(cth*cuWIm) + I*cth*cuWRe + cuBIm*sth - I*cuBRe*sth)*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] , V[4, {e3x2}] ] == {{(cuGIm + I*cuGRe)*gc60*SUNT[e3x2, e1x3, e2x3]*yutop[e1x2, e2x2], 0}, {0, 0}, {-((cuGIm - I*cuGRe)*gc60*SUNT[e3x2, e1x3, e2x3]*yutop[e2x2, e1x2]), 0}, {0, 0}, {-((cuGIm + I*cuGRe)*gc60*SUNT[e3x2, e1x3, e2x3]*yutop[e1x2, e2x2]), 0}, {0, 0}, {(cuGIm - I*cuGRe)*gc60*SUNT[e3x2, e1x3, e2x3]*yutop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{-((cuGIm + I*cuGRe)*gc61*(SUNT[e3x2, e4x2, e1x3, e2x3] - SUNT[e4x2, e3x2, e1x3, e2x3])*yutop[e1x2, e2x2]), 0}, {0, 0}, {(cuGIm - I*cuGRe)*gc61*(SUNT[e3x2, e4x2, e1x3, e2x3] - SUNT[e4x2, e3x2, e1x3, e2x3])*yutop[e2x2, e1x2], 0}, {0, 0}, {(cuGIm + I*cuGRe)*gc61*(SUNT[e3x2, e4x2, e1x3, e2x3] - SUNT[e4x2, e3x2, e1x3, e2x3])*yutop[e1x2, e2x2], 0}, {0, 0}, {-((cuGIm - I*cuGRe)*gc61*(SUNT[e3x2, e4x2, e1x3, e2x3] - SUNT[e4x2, e3x2, e1x3, e2x3])*yutop[e2x2, e1x2]), 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{-((cuGIm + I*cuGRe)*gc62*(SUNT[e3x2, e4x2, e1x3, e2x3] - SUNT[e4x2, e3x2, e1x3, e2x3])*yutop[e1x2, e2x2]), 0}, {0, 0}, {(cuGIm - I*cuGRe)*gc62*(SUNT[e3x2, e4x2, e1x3, e2x3] - SUNT[e4x2, e3x2, e1x3, e2x3])*yutop[e2x2, e1x2], 0}, {0, 0}, {(cuGIm + I*cuGRe)*gc62*(SUNT[e3x2, e4x2, e1x3, e2x3] - SUNT[e4x2, e3x2, e1x3, e2x3])*yutop[e1x2, e2x2], 0}, {0, 0}, {-((cuGIm - I*cuGRe)*gc62*(SUNT[e3x2, e4x2, e1x3, e2x3] - SUNT[e4x2, e3x2, e1x3, e2x3])*yutop[e2x2, e1x2]), 0}, {0, 0}},

C[ -F[40, {e1x2}] , F[30, {e2x2}] , S[1] , -V[3] ] == {{-((cbWIm + I*cbWRe)*gc63*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {(ctWIm - I*ctWRe)*gc63*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(cbWIm + I*cbWRe)*gc63*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-((ctWIm - I*ctWRe)*gc63*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[40, {e1x2}] , F[30, {e2x2}] , S[1] , V[1] , -V[3] ] == {{-((cbWIm + I*cbWRe)*gc64*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {(ctWIm - I*ctWRe)*gc64*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(cbWIm + I*cbWRe)*gc64*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-((ctWIm - I*ctWRe)*gc64*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[40, {e1x2}] , F[30, {e2x2}] , V[1] , -V[3] ] == {{-((cbWIm + I*cbWRe)*gc65*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {(ctWIm - I*ctWRe)*gc65*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(cbWIm + I*cbWRe)*gc65*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-((ctWIm - I*ctWRe)*gc65*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[40, {e1x2}] , F[40, {e2x2}] , S[1] , V[3] , -V[3] ] == {{-((cbWIm + I*cbWRe)*gc66*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {(cbWIm - I*cbWRe)*gc66*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(cbWIm + I*cbWRe)*gc66*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-((cbWIm - I*cbWRe)*gc66*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[40, {e1x2}] , F[40, {e2x2}] , V[3] , -V[3] ] == {{-((cbWIm + I*cbWRe)*gc67*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {(cbWIm - I*cbWRe)*gc67*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(cbWIm + I*cbWRe)*gc67*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-((cbWIm - I*cbWRe)*gc67*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[40, {e1x2}] , F[30, {e2x2}] , S[1] , -V[3] , V[2] ] == {{-((cbWIm + I*cbWRe)*gc68*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {(ctWIm - I*ctWRe)*gc68*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(cbWIm + I*cbWRe)*gc68*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-((ctWIm - I*ctWRe)*gc68*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[40, {e1x2}] , F[30, {e2x2}] , -V[3] , V[2] ] == {{-((cbWIm + I*cbWRe)*gc69*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {(ctWIm - I*ctWRe)*gc69*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(cbWIm + I*cbWRe)*gc69*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-((ctWIm - I*ctWRe)*gc69*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , S[1] , -V[3] ] == {{-(((ceWIm + I*ceWRe)*gc70[e1x2, e2x2])/(ceWIm + ceWRe)), 0}, {0, 0}, {0, 0}, {0, 0}, {((ceWIm + I*ceWRe)*gc70[e1x2, e2x2])/(ceWIm + ceWRe), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , S[1] , V[1] , -V[3] ] == {{-(((ceWIm + I*ceWRe)*gc71[e1x2, e2x2])/(ceWIm + ceWRe)), 0}, {0, 0}, {0, 0}, {0, 0}, {((ceWIm + I*ceWRe)*gc71[e1x2, e2x2])/(ceWIm + ceWRe), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , V[1] , -V[3] ] == {{-(((ceWIm + I*ceWRe)*gc72[e1x2, e2x2])/(ceWIm + ceWRe)), 0}, {0, 0}, {0, 0}, {0, 0}, {((ceWIm + I*ceWRe)*gc72[e1x2, e2x2])/(ceWIm + ceWRe), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[1] , V[3] , -V[3] ] == {{(ceWIm + I*ceWRe)*gc73*yl[e1x2, e2x2], 0}, {0, 0}, {-((ceWIm - I*ceWRe)*gc73*yl[e2x2, e1x2]), 0}, {0, 0}, {-((ceWIm + I*ceWRe)*gc73*yl[e1x2, e2x2]), 0}, {0, 0}, {(ceWIm - I*ceWRe)*gc73*yl[e2x2, e1x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[3] , -V[3] ] == {{(ceWIm + I*ceWRe)*gc74*yl[e1x2, e2x2], 0}, {0, 0}, {-((ceWIm - I*ceWRe)*gc74*yl[e2x2, e1x2]), 0}, {0, 0}, {-((ceWIm + I*ceWRe)*gc74*yl[e1x2, e2x2]), 0}, {0, 0}, {(ceWIm - I*ceWRe)*gc74*yl[e2x2, e1x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , S[1] , -V[3] , V[2] ] == {{-(((ceWIm + I*ceWRe)*gc75[e1x2, e2x2])/(ceWIm + ceWRe)), 0}, {0, 0}, {0, 0}, {0, 0}, {((ceWIm + I*ceWRe)*gc75[e1x2, e2x2])/(ceWIm + ceWRe), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -V[3] , V[2] ] == {{-(((ceWIm + I*ceWRe)*gc76[e1x2, e2x2])/(ceWIm + ceWRe)), 0}, {0, 0}, {0, 0}, {0, 0}, {((ceWIm + I*ceWRe)*gc76[e1x2, e2x2])/(ceWIm + ceWRe), 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[40, {e2x2}] , S[1] , V[3] ] == {{-((ctWIm + I*ctWRe)*gc77*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {(cbWIm - I*cbWRe)*gc77*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(ctWIm + I*ctWRe)*gc77*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-((cbWIm - I*cbWRe)*gc77*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[40, {e2x2}] , S[1] , V[1] , V[3] ] == {{-((ctWIm + I*ctWRe)*gc78*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {(cbWIm - I*cbWRe)*gc78*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(ctWIm + I*ctWRe)*gc78*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-((cbWIm - I*cbWRe)*gc78*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[40, {e2x2}] , V[1] , V[3] ] == {{-((ctWIm + I*ctWRe)*gc79*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {(cbWIm - I*cbWRe)*gc79*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(ctWIm + I*ctWRe)*gc79*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-((cbWIm - I*cbWRe)*gc79*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[30, {e2x2}] , S[1] , V[3] , -V[3] ] == {{-((ctWIm + I*ctWRe)*gc80*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {(ctWIm - I*ctWRe)*gc80*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(ctWIm + I*ctWRe)*gc80*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-((ctWIm - I*ctWRe)*gc80*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[30, {e2x2}] , V[3] , -V[3] ] == {{-((ctWIm + I*ctWRe)*gc81*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {(ctWIm - I*ctWRe)*gc81*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(ctWIm + I*ctWRe)*gc81*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-((ctWIm - I*ctWRe)*gc81*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[40, {e2x2}] , S[1] , V[3] , V[2] ] == {{-((ctWIm + I*ctWRe)*gc82*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {(cbWIm - I*cbWRe)*gc82*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(ctWIm + I*ctWRe)*gc82*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-((cbWIm - I*cbWRe)*gc82*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[30, {e1x2}] , F[40, {e2x2}] , V[3] , V[2] ] == {{-((ctWIm + I*ctWRe)*gc83*IndexDelta[e1x2, e2x2]), 0}, {0, 0}, {(cbWIm - I*cbWRe)*gc83*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {(ctWIm + I*ctWRe)*gc83*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {-((cbWIm - I*cbWRe)*gc83*IndexDelta[e1x2, e2x2]), 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] , -V[3] ] == {{(cdWIm + I*cdWRe)*gc84*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2], 0}, {0, 0}, {-((cuWIm - I*cuWRe)*gc84*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2]), 0}, {0, 0}, {-((cdWIm + I*cdWRe)*gc84*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2]), 0}, {0, 0}, {(cuWIm - I*cuWRe)*gc84*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] , V[1] , -V[3] ] == {{(cdWIm + I*cdWRe)*gc85*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2], 0}, {0, 0}, {-((cuWIm - I*cuWRe)*gc85*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2]), 0}, {0, 0}, {-((cdWIm + I*cdWRe)*gc85*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2]), 0}, {0, 0}, {(cuWIm - I*cuWRe)*gc85*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[1] , -V[3] ] == {{(cdWIm + I*cdWRe)*gc86*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2], 0}, {0, 0}, {-((cuWIm - I*cuWRe)*gc86*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2]), 0}, {0, 0}, {-((cdWIm + I*cdWRe)*gc86*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2]), 0}, {0, 0}, {(cuWIm - I*cuWRe)*gc86*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] , V[3] , -V[3] ] == {{(cdWIm + I*cdWRe)*gc87*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2], 0}, {0, 0}, {-((cdWIm - I*cdWRe)*gc87*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2]), 0}, {0, 0}, {-((cdWIm + I*cdWRe)*gc87*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2]), 0}, {0, 0}, {(cdWIm - I*cdWRe)*gc87*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[3] , -V[3] ] == {{(cdWIm + I*cdWRe)*gc88*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2], 0}, {0, 0}, {-((cdWIm - I*cdWRe)*gc88*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2]), 0}, {0, 0}, {-((cdWIm + I*cdWRe)*gc88*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2]), 0}, {0, 0}, {(cdWIm - I*cdWRe)*gc88*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] , -V[3] , V[2] ] == {{(cdWIm + I*cdWRe)*gc89*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2], 0}, {0, 0}, {-((cuWIm - I*cuWRe)*gc89*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2]), 0}, {0, 0}, {-((cdWIm + I*cdWRe)*gc89*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2]), 0}, {0, 0}, {(cuWIm - I*cuWRe)*gc89*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -V[3] , V[2] ] == {{(cdWIm + I*cdWRe)*gc90*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2], 0}, {0, 0}, {-((cuWIm - I*cuWRe)*gc90*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2]), 0}, {0, 0}, {-((cdWIm + I*cdWRe)*gc90*IndexDelta[e1x3, e2x3]*ydtop[e1x2, e2x2]), 0}, {0, 0}, {(cuWIm - I*cuWRe)*gc90*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] , V[3] ] == {{(cuWIm + I*cuWRe)*gc91*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2], 0}, {0, 0}, {-((cdWIm - I*cdWRe)*gc91*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2]), 0}, {0, 0}, {-((cuWIm + I*cuWRe)*gc91*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2]), 0}, {0, 0}, {(cdWIm - I*cdWRe)*gc91*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] , V[1] , V[3] ] == {{(cuWIm + I*cuWRe)*gc92*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2], 0}, {0, 0}, {-((cdWIm - I*cdWRe)*gc92*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2]), 0}, {0, 0}, {-((cuWIm + I*cuWRe)*gc92*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2]), 0}, {0, 0}, {(cdWIm - I*cdWRe)*gc92*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[1] , V[3] ] == {{(cuWIm + I*cuWRe)*gc93*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2], 0}, {0, 0}, {-((cdWIm - I*cdWRe)*gc93*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2]), 0}, {0, 0}, {-((cuWIm + I*cuWRe)*gc93*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2]), 0}, {0, 0}, {(cdWIm - I*cdWRe)*gc93*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] , V[3] , -V[3] ] == {{(cuWIm + I*cuWRe)*gc94*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2], 0}, {0, 0}, {-((cuWIm - I*cuWRe)*gc94*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2]), 0}, {0, 0}, {-((cuWIm + I*cuWRe)*gc94*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2]), 0}, {0, 0}, {(cuWIm - I*cuWRe)*gc94*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[3] , -V[3] ] == {{(cuWIm + I*cuWRe)*gc95*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2], 0}, {0, 0}, {-((cuWIm - I*cuWRe)*gc95*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2]), 0}, {0, 0}, {-((cuWIm + I*cuWRe)*gc95*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2]), 0}, {0, 0}, {(cuWIm - I*cuWRe)*gc95*IndexDelta[e1x3, e2x3]*yutop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] , V[3] , V[2] ] == {{(cuWIm + I*cuWRe)*gc96*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2], 0}, {0, 0}, {-((cdWIm - I*cdWRe)*gc96*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2]), 0}, {0, 0}, {-((cuWIm + I*cuWRe)*gc96*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2]), 0}, {0, 0}, {(cdWIm - I*cdWRe)*gc96*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[3] , V[2] ] == {{(cuWIm + I*cuWRe)*gc97*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2], 0}, {0, 0}, {-((cdWIm - I*cdWRe)*gc97*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2]), 0}, {0, 0}, {-((cuWIm + I*cuWRe)*gc97*IndexDelta[e1x3, e2x3]*yutop[e1x2, e2x2]), 0}, {0, 0}, {(cdWIm - I*cdWRe)*gc97*IndexDelta[e1x3, e2x3]*ydtop[e2x2, e1x2], 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , S[1] , V[3] ] == {{0, 0}, {0, 0}, {-(((ceWIm - I*ceWRe)*gc98[e1x2, e2x2])/(ceWIm - ceWRe)), 0}, {0, 0}, {0, 0}, {0, 0}, {((ceWIm - I*ceWRe)*gc98[e1x2, e2x2])/(ceWIm - ceWRe), 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , S[1] , V[1] , V[3] ] == {{0, 0}, {0, 0}, {-(((ceWIm - I*ceWRe)*gc99[e1x2, e2x2])/(ceWIm - ceWRe)), 0}, {0, 0}, {0, 0}, {0, 0}, {((ceWIm - I*ceWRe)*gc99[e1x2, e2x2])/(ceWIm - ceWRe), 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , V[1] , V[3] ] == {{0, 0}, {0, 0}, {((ceWIm - I*ceWRe)*gc100[e1x2, e2x2])/(-ceWIm + ceWRe), 0}, {0, 0}, {0, 0}, {0, 0}, {((ceWIm - I*ceWRe)*gc100[e1x2, e2x2])/(ceWIm - ceWRe), 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , S[1] , V[3] , V[2] ] == {{0, 0}, {0, 0}, {-(((ceWIm - I*ceWRe)*gc101[e1x2, e2x2])/(ceWIm - ceWRe)), 0}, {0, 0}, {0, 0}, {0, 0}, {((ceWIm - I*ceWRe)*gc101[e1x2, e2x2])/(ceWIm - ceWRe), 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , V[3] , V[2] ] == {{0, 0}, {0, 0}, {-(((ceWIm - I*ceWRe)*gc102[e1x2, e2x2])/(ceWIm - ceWRe)), 0}, {0, 0}, {0, 0}, {0, 0}, {((ceWIm - I*ceWRe)*gc102[e1x2, e2x2])/(ceWIm - ceWRe), 0}, {0, 0}},

C[ -F[40, {e1x2}] , -F[4, {e3x2, e3x3}] , F[40, {e2x2}] , F[4, {e4x2, e4x3}] ] == {{I*gc103*IndexDelta[e3x2, e4x2]*(3*cbj8*IndexDelta[e1x2, e4x3]*IndexDelta[e2x2, e3x3] + (6*cbj1 - cbj8)*IndexDelta[e1x2, e2x2]*IndexDelta[e3x3, e4x3]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {-(gc103*((6*cjQbd1Im - (6*I)*cjQbd1Re - cjQbd8Im + I*cjQbd8Re)*IndexDelta[e1x2, e4x3]*IndexDelta[e2x2, e3x3] + 3*(cjQbd8Im - I*cjQbd8Re)*IndexDelta[e1x2, e2x2]*IndexDelta[e3x3, e4x3])*ydtop[e4x2, e3x2]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {gc103*((6*cjQbd1Im + (6*I)*cjQbd1Re - cjQbd8Im - I*cjQbd8Re)*IndexDelta[e1x2, e4x3]*IndexDelta[e2x2, e3x3] + 3*(cjQbd8Im + I*cjQbd8Re)*IndexDelta[e1x2, e2x2]*IndexDelta[e3x3, e4x3])*ydtop[e3x2, e4x2], 0}, {0, 0}, {I*gc103*IndexDelta[e3x2, e4x2]*(3*cQd8*IndexDelta[e1x2, e4x3]*IndexDelta[e2x2, e3x3] + (6*cQd1 - cQd8)*IndexDelta[e1x2, e2x2]*IndexDelta[e3x3, e4x3]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , -F[30, {e3x2}] , F[40, {e2x2}] , F[3, {e4x2, e4x3}] ] == {{gc104*(-3*(cjQbd8Im + I*cjQbd8Re)*IndexDelta[e1x3, e4x3]*IndexDelta[e2x2, e3x2] + (-6*cjQbd1Im - (6*I)*cjQbd1Re + cjQbd8Im + I*cjQbd8Re)*IndexDelta[e1x3, e2x2]*IndexDelta[e3x2, e4x3])*ydtop[e1x2, e4x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {gc104*(3*(cjQtu8Im - I*cjQtu8Re)*IndexDelta[e1x3, e4x3]*IndexDelta[e2x2, e3x2] + (6*cjQtu1Im - (6*I)*cjQtu1Re - cjQtu8Im + I*cjQtu8Re)*IndexDelta[e1x3, e2x2]*IndexDelta[e3x2, e4x3])*yutop[e4x2, e1x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[30, {e1x2}] , -F[3, {e3x2, e3x3}] , F[30, {e2x2}] , F[3, {e4x2, e4x3}] ] == {{I*gc105*IndexDelta[e3x2, e4x2]*(3*ctj8*IndexDelta[e1x2, e4x3]*IndexDelta[e2x2, e3x3] + (6*ctj1 - ctj8)*IndexDelta[e1x2, e2x2]*IndexDelta[e3x3, e4x3]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {-(gc105*((6*cjQtu1Im - (6*I)*cjQtu1Re - cjQtu8Im + I*cjQtu8Re)*IndexDelta[e1x2, e4x3]*IndexDelta[e2x2, e3x3] + 3*(cjQtu8Im - I*cjQtu8Re)*IndexDelta[e1x2, e2x2]*IndexDelta[e3x3, e4x3])*yutop[e4x2, e3x2]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {gc105*((6*cjQtu1Im + (6*I)*cjQtu1Re - cjQtu8Im - I*cjQtu8Re)*IndexDelta[e1x2, e4x3]*IndexDelta[e2x2, e3x3] + 3*(cjQtu8Im + I*cjQtu8Re)*IndexDelta[e1x2, e2x2]*IndexDelta[e3x3, e4x3])*yutop[e3x2, e4x2], 0}, {0, 0}, {I*gc105*IndexDelta[e3x2, e4x2]*(3*cQu8*IndexDelta[e1x2, e4x3]*IndexDelta[e2x2, e3x3] + (6*cQu1 - cQu8)*IndexDelta[e1x2, e2x2]*IndexDelta[e3x3, e4x3]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[40, {e1x2}] , -F[3, {e3x2, e3x3}] , F[4, {e2x2, e2x3}] , F[30, {e4x2}] ] == {{gc106*(3*(cjQbd8Im - I*cjQbd8Re)*IndexDelta[e1x2, e4x2]*IndexDelta[e2x3, e3x3] + (6*cjQbd1Im - (6*I)*cjQbd1Re - cjQbd8Im + I*cjQbd8Re)*IndexDelta[e1x2, e2x3]*IndexDelta[e3x3, e4x2])*ydtop[e2x2, e3x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {-(gc106*(3*(cjQtu8Im + I*cjQtu8Re)*IndexDelta[e1x2, e4x2]*IndexDelta[e2x3, e3x3] + (6*cjQtu1Im + (6*I)*cjQtu1Re - cjQtu8Im - I*cjQtu8Re)*IndexDelta[e1x2, e2x3]*IndexDelta[e3x3, e4x2])*yutop[e3x2, e2x2]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[40, {e1x2}] , -F[40, {e3x2}] , F[40, {e2x2}] , F[40, {e4x2}] ] == {{I*gc107*(3*cQb8*IndexDelta[e1x2, e4x2]*IndexDelta[e2x2, e3x2] + (6*cQb1 - cQb8)*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc107*((6*cQb1 - cQb8)*IndexDelta[e1x2, e4x2]*IndexDelta[e2x2, e3x2] + 3*cQb8*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc107*((6*cQb1 - cQb8)*IndexDelta[e1x2, e4x2]*IndexDelta[e2x2, e3x2] + 3*cQb8*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2]), 0}, {0, 0}, {I*gc107*(3*cQb8*IndexDelta[e1x2, e4x2]*IndexDelta[e2x2, e3x2] + (6*cQb1 - cQb8)*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , -F[4, {e3x2, e3x3}] , F[4, {e2x2, e2x3}] , F[4, {e4x2, e4x3}] ] == {{((I/2)*gc108*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2]*(3*cjd8*IndexDelta[e1x3, e4x3]*IndexDelta[e2x3, e3x3] + (6*cjd1 - cjd8)*IndexDelta[e1x3, e2x3]*IndexDelta[e3x3, e4x3]))/(3*cjd1 + cjd8), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {((I/2)*gc108*IndexDelta[e1x2, e4x2]*IndexDelta[e2x2, e3x2]*((6*cjd1 - cjd8)*IndexDelta[e1x3, e4x3]*IndexDelta[e2x3, e3x3] + 3*cjd8*IndexDelta[e1x3, e2x3]*IndexDelta[e3x3, e4x3]))/(3*cjd1 + cjd8), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {((I/2)*gc108*IndexDelta[e1x2, e4x2]*IndexDelta[e2x2, e3x2]*((6*cjd1 - cjd8)*IndexDelta[e1x3, e4x3]*IndexDelta[e2x3, e3x3] + 3*cjd8*IndexDelta[e1x3, e2x3]*IndexDelta[e3x3, e4x3]))/(3*cjd1 + cjd8), 0}, {0, 0}, {((I/2)*gc108*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2]*(3*cjd8*IndexDelta[e1x3, e4x3]*IndexDelta[e2x3, e3x3] + (6*cjd1 - cjd8)*IndexDelta[e1x3, e2x3]*IndexDelta[e3x3, e4x3]))/(3*cjd1 + cjd8), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[40, {e1x2}] , -F[2, {e3x2}] , F[40, {e2x2}] , F[2, {e4x2}] ] == {{I*cbl*gc109*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*cQe*gc109*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , -F[2, {e3x2}] , F[4, {e2x2, e2x3}] , F[2, {e4x2}] ] == {{I*cld*gc110*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3]*IndexDelta[e3x2, e4x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*cje*gc110*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3]*IndexDelta[e3x2, e4x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2, {e1x2}] , -F[2, {e3x2}] , F[2, {e2x2}] , F[2, {e4x2}] ] == {{I*gc111*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc111*IndexDelta[e1x2, e4x2]*IndexDelta[e2x2, e3x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc111*IndexDelta[e1x2, e4x2]*IndexDelta[e2x2, e3x2], 0}, {0, 0}, {I*gc111*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2, {e1x2}] , -F[30, {e3x2}] , F[2, {e2x2}] , F[30, {e4x2}] ] == {{I*cQe*gc112*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*ctl*gc112*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[40, {e1x2}] , -F[30, {e3x2}] , F[40, {e2x2}] , F[30, {e4x2}] ] == {{I*gc113*(3*cQb8*IndexDelta[e1x2, e4x2]*IndexDelta[e2x2, e3x2] + (6*cQb1 - cQb8)*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc113*(3*cQt8*IndexDelta[e1x2, e4x2]*IndexDelta[e2x2, e3x2] + (6*cQt1 - cQt8)*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , -F[30, {e3x2}] , F[4, {e2x2, e2x3}] , F[30, {e4x2}] ] == {{(I/2)*gc114*IndexDelta[e1x2, e2x2]*(3*cQd8*IndexDelta[e1x3, e4x2]*IndexDelta[e2x3, e3x2] + (6*cQd1 - cQd8)*IndexDelta[e1x3, e2x3]*IndexDelta[e3x2, e4x2]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {(I/2)*gc114*IndexDelta[e1x2, e2x2]*(3*ctj8*IndexDelta[e1x3, e4x2]*IndexDelta[e2x3, e3x2] + (6*ctj1 - ctj8)*IndexDelta[e1x3, e2x3]*IndexDelta[e3x2, e4x2]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[30, {e1x2}] , -F[30, {e3x2}] , F[30, {e2x2}] , F[30, {e4x2}] ] == {{I*gc115*(3*cQt8*IndexDelta[e1x2, e4x2]*IndexDelta[e2x2, e3x2] + (6*cQt1 - cQt8)*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc115*((6*cQt1 - cQt8)*IndexDelta[e1x2, e4x2]*IndexDelta[e2x2, e3x2] + 3*cQt8*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc115*((6*cQt1 - cQt8)*IndexDelta[e1x2, e4x2]*IndexDelta[e2x2, e3x2] + 3*cQt8*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2]), 0}, {0, 0}, {I*gc115*(3*cQt8*IndexDelta[e1x2, e4x2]*IndexDelta[e2x2, e3x2] + (6*cQt1 - cQt8)*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2, {e1x2}] , -F[3, {e3x2, e3x3}] , F[2, {e2x2}] , F[3, {e4x2, e4x3}] ] == {{I*cje*gc116*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2]*IndexDelta[e3x3, e4x3], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*clu*gc116*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2]*IndexDelta[e3x3, e4x3], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[40, {e1x2}] , -F[3, {e3x2, e3x3}] , F[40, {e2x2}] , F[3, {e4x2, e4x3}] ] == {{I*gc117*IndexDelta[e3x2, e4x2]*(3*cbj8*IndexDelta[e1x2, e4x3]*IndexDelta[e2x2, e3x3] + (6*cbj1 - cbj8)*IndexDelta[e1x2, e2x2]*IndexDelta[e3x3, e4x3]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc117*IndexDelta[e3x2, e4x2]*(3*cQu8*IndexDelta[e1x2, e4x3]*IndexDelta[e2x2, e3x3] + (6*cQu1 - cQu8)*IndexDelta[e1x2, e2x2]*IndexDelta[e3x3, e4x3]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , -F[3, {e3x2, e3x3}] , F[4, {e2x2, e2x3}] , F[3, {e4x2, e4x3}] ] == {{(I/2)*gc118*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2]*(3*cjd8*IndexDelta[e1x3, e4x3]*IndexDelta[e2x3, e3x3] + (6*cjd1 - cjd8)*IndexDelta[e1x3, e2x3]*IndexDelta[e3x3, e4x3]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {(I/2)*gc118*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2]*(3*cju8*IndexDelta[e1x3, e4x3]*IndexDelta[e2x3, e3x3] + (6*cju1 - cju8)*IndexDelta[e1x3, e2x3]*IndexDelta[e3x3, e4x3]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , -F[3, {e3x2, e3x3}] , F[3, {e2x2, e2x3}] , F[3, {e4x2, e4x3}] ] == {{((I/2)*gc119*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2]*(3*cju8*IndexDelta[e1x3, e4x3]*IndexDelta[e2x3, e3x3] + (6*cju1 - cju8)*IndexDelta[e1x3, e2x3]*IndexDelta[e3x3, e4x3]))/(3*cju1 + cju8), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {((I/2)*gc119*IndexDelta[e1x2, e4x2]*IndexDelta[e2x2, e3x2]*((6*cju1 - cju8)*IndexDelta[e1x3, e4x3]*IndexDelta[e2x3, e3x3] + 3*cju8*IndexDelta[e1x3, e2x3]*IndexDelta[e3x3, e4x3]))/(3*cju1 + cju8), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {((I/2)*gc119*IndexDelta[e1x2, e4x2]*IndexDelta[e2x2, e3x2]*((6*cju1 - cju8)*IndexDelta[e1x3, e4x3]*IndexDelta[e2x3, e3x3] + 3*cju8*IndexDelta[e1x3, e2x3]*IndexDelta[e3x3, e4x3]))/(3*cju1 + cju8), 0}, {0, 0}, {((I/2)*gc119*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2]*(3*cju8*IndexDelta[e1x3, e4x3]*IndexDelta[e2x3, e3x3] + (6*cju1 - cju8)*IndexDelta[e1x3, e2x3]*IndexDelta[e3x3, e4x3]))/(3*cju1 + cju8), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[40, {e1x2}] , -F[1, {e3x2}] , F[40, {e2x2}] , F[1, {e4x2}] ] == {{I*gc120*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , -F[1, {e3x2}] , F[4, {e2x2, e2x3}] , F[1, {e4x2}] ] == {{I*gc121*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3]*IndexDelta[e3x2, e4x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[30, {e1x2}] , -F[1, {e3x2}] , F[30, {e2x2}] , F[1, {e4x2}] ] == {{I*gc122*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , -F[1, {e3x2}] , F[3, {e2x2, e2x3}] , F[1, {e4x2}] ] == {{I*gc123*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3]*IndexDelta[e3x2, e4x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2, {e1x2}] , -F[1, {e3x2}] , F[2, {e2x2}] , F[1, {e4x2}] ] == {{I*gc124*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc3 -> GS,
     gc4 -> -GS^2,
     gc5 -> EL/3,
     gc6 -> EL/3,
     gc7 -> EL,
     gc8 -> (-2*EL)/3,
     gc9 -> (-2*EL)/3,
     gc10 -> -(yb/Sqrt[2]),
     gc11 -> -(yt/Sqrt[2]),
     gc12 -> -EL,
     gc15 -> -EL^2,
     gc16 -> -((cth*EL)/sth),
     gc17 -> EL^2/sth^2,
     gc18[e1x2_, e2x2_] -> -(ydtop[e1x2, e2x2]/Sqrt[2]),
     gc19[e1x2_, e2x2_] -> -(yl[e1x2, e2x2]/Sqrt[2]),
     gc20[e1x2_, e2x2_] -> -(yutop[e1x2, e2x2]/Sqrt[2]),
     gc21 -> (cth*EL^2)/sth,
     gc24 -> (EL^2*(-1 + sth^2))/sth^2,
     gc25 -> -GS,
     gc26 -> -GS,
     gc27 -> -GS,
     gc28 -> -GS,
     gc29 -> -(EL/(Sqrt[2]*sth)),
     gc30 -> -(EL/(Sqrt[2]*sth)),
     gc31 -> -(EL/(Sqrt[2]*sth)),
     gc32 -> -(EL/(Sqrt[2]*sth)),
     gc33 -> -(EL/(Sqrt[2]*sth)),
     gc34 -> -(EL/(Sqrt[2]*sth)),
     gc35 -> -(EL*(-3 + 2*sth^2))/(6*cth*sth),
     gc36 -> -(EL*(-3 + 2*sth^2))/(6*cth*sth),
     gc37 -> -(EL*(-1 + 2*sth^2))/(2*cth*sth),
     gc38 -> (EL*(-3 + 4*sth^2))/(6*cth*sth),
     gc39 -> (EL*(-3 + 4*sth^2))/(6*cth*sth),
     gc40 -> -EL/(2*cth*sth),
     gc41 -> 1/(Sqrt[2]*LambdaSMEFT^2),
     gc42 -> -(1/(Sqrt[2]*LambdaSMEFT^2)),
     gc43 -> -(1/(Sqrt[2]*LambdaSMEFT^2)),
     gc44 -> 1/(Sqrt[2]*LambdaSMEFT^2),
     gc45 -> 1/(Sqrt[2]*LambdaSMEFT^2),
     gc46 -> -(1/(Sqrt[2]*LambdaSMEFT^2)),
     gc47 -> 1/(Sqrt[2]*LambdaSMEFT^2),
     gc48 -> -(GS/(Sqrt[2]*LambdaSMEFT^2)),
     gc49 -> -((GS*vevhat)/(Sqrt[2]*LambdaSMEFT^2)),
     gc50 -> 1/(Sqrt[2]*LambdaSMEFT^2),
     gc51 -> -(GS/(Sqrt[2]*LambdaSMEFT^2)),
     gc52 -> -((GS*vevhat)/(Sqrt[2]*LambdaSMEFT^2)),
     gc53 -> -(1/(Sqrt[2]*LambdaSMEFT^2)),
     gc54 -> 1/(Sqrt[2]*LambdaSMEFT^2),
     gc55 -> -(1/(Sqrt[2]*LambdaSMEFT^2)),
     gc56 -> GS/(Sqrt[2]*LambdaSMEFT^2),
     gc57 -> (GS*vevhat)/(Sqrt[2]*LambdaSMEFT^2),
     gc58 -> -(1/(Sqrt[2]*LambdaSMEFT^2)),
     gc59 -> 1/(Sqrt[2]*LambdaSMEFT^2),
     gc60 -> -(1/(Sqrt[2]*LambdaSMEFT^2)),
     gc61 -> GS/(Sqrt[2]*LambdaSMEFT^2),
     gc62 -> (GS*vevhat)/(Sqrt[2]*LambdaSMEFT^2),
     gc63 -> LambdaSMEFT^(-2),
     gc64 -> -(EL/LambdaSMEFT^2),
     gc65 -> -((EL*vevhat)/LambdaSMEFT^2),
     gc66 -> -(EL/(Sqrt[2]*LambdaSMEFT^2*sth)),
     gc67 -> -((EL*vevhat)/(Sqrt[2]*LambdaSMEFT^2*sth)),
     gc68 -> (cth*EL)/(LambdaSMEFT^2*sth),
     gc69 -> (cth*EL*vevhat)/(LambdaSMEFT^2*sth),
     gc70[e1x2_, e2x2_] -> ((ceWIm + ceWRe)*yl[e1x2, e2x2])/LambdaSMEFT^2,
     gc71[e1x2_, e2x2_] -> -(((ceWIm + ceWRe)*EL*yl[e1x2, e2x2])/LambdaSMEFT^2),
     gc72[e1x2_, e2x2_] -> -(((ceWIm + ceWRe)*EL*vevhat*yl[e1x2, e2x2])/LambdaSMEFT^2),
     gc73 -> EL/(Sqrt[2]*LambdaSMEFT^2*sth),
     gc74 -> (EL*vevhat)/(Sqrt[2]*LambdaSMEFT^2*sth),
     gc75[e1x2_, e2x2_] -> ((ceWIm + ceWRe)*cth*EL*yl[e1x2, e2x2])/(LambdaSMEFT^2*sth),
     gc76[e1x2_, e2x2_] -> ((ceWIm + ceWRe)*cth*EL*vevhat*yl[e1x2, e2x2])/(LambdaSMEFT^2*sth),
     gc77 -> LambdaSMEFT^(-2),
     gc78 -> EL/LambdaSMEFT^2,
     gc79 -> (EL*vevhat)/LambdaSMEFT^2,
     gc80 -> EL/(Sqrt[2]*LambdaSMEFT^2*sth),
     gc81 -> (EL*vevhat)/(Sqrt[2]*LambdaSMEFT^2*sth),
     gc82 -> -((cth*EL)/(LambdaSMEFT^2*sth)),
     gc83 -> -((cth*EL*vevhat)/(LambdaSMEFT^2*sth)),
     gc84 -> -LambdaSMEFT^(-2),
     gc85 -> EL/LambdaSMEFT^2,
     gc86 -> (EL*vevhat)/LambdaSMEFT^2,
     gc87 -> EL/(Sqrt[2]*LambdaSMEFT^2*sth),
     gc88 -> (EL*vevhat)/(Sqrt[2]*LambdaSMEFT^2*sth),
     gc89 -> -((cth*EL)/(LambdaSMEFT^2*sth)),
     gc90 -> -((cth*EL*vevhat)/(LambdaSMEFT^2*sth)),
     gc91 -> -LambdaSMEFT^(-2),
     gc92 -> -(EL/LambdaSMEFT^2),
     gc93 -> -((EL*vevhat)/LambdaSMEFT^2),
     gc94 -> -(EL/(Sqrt[2]*LambdaSMEFT^2*sth)),
     gc95 -> -((EL*vevhat)/(Sqrt[2]*LambdaSMEFT^2*sth)),
     gc96 -> (cth*EL)/(LambdaSMEFT^2*sth),
     gc97 -> (cth*EL*vevhat)/(LambdaSMEFT^2*sth),
     gc98[e1x2_, e2x2_] -> -(((ceWIm - ceWRe)*yl[e2x2, e1x2])/LambdaSMEFT^2),
     gc99[e1x2_, e2x2_] -> -(((ceWIm - ceWRe)*EL*yl[e2x2, e1x2])/LambdaSMEFT^2),
     gc100[e1x2_, e2x2_] -> ((-ceWIm + ceWRe)*EL*vevhat*yl[e2x2, e1x2])/LambdaSMEFT^2,
     gc101[e1x2_, e2x2_] -> ((ceWIm - ceWRe)*cth*EL*yl[e2x2, e1x2])/(LambdaSMEFT^2*sth),
     gc102[e1x2_, e2x2_] -> ((ceWIm - ceWRe)*cth*EL*vevhat*yl[e2x2, e1x2])/(LambdaSMEFT^2*sth),
     gc103 -> 1/(6*LambdaSMEFT^2),
     gc104 -> -1/(6*LambdaSMEFT^2),
     gc105 -> 1/(6*LambdaSMEFT^2),
     gc106 -> -1/(6*LambdaSMEFT^2),
     gc107 -> 1/(6*LambdaSMEFT^2),
     gc108 -> (3*cjd1 + cjd8)/(3*LambdaSMEFT^2),
     gc109 -> LambdaSMEFT^(-2),
     gc110 -> LambdaSMEFT^(-2),
     gc111 -> cle/LambdaSMEFT^2,
     gc112 -> LambdaSMEFT^(-2),
     gc113 -> 1/(6*LambdaSMEFT^2),
     gc114 -> 1/(3*LambdaSMEFT^2),
     gc115 -> 1/(6*LambdaSMEFT^2),
     gc116 -> LambdaSMEFT^(-2),
     gc117 -> 1/(6*LambdaSMEFT^2),
     gc118 -> 1/(3*LambdaSMEFT^2),
     gc119 -> (3*cju1 + cju8)/(3*LambdaSMEFT^2),
     gc120 -> cbl/LambdaSMEFT^2,
     gc121 -> cld/LambdaSMEFT^2,
     gc122 -> ctl/LambdaSMEFT^2,
     gc123 -> clu/LambdaSMEFT^2,
     gc124 -> cle/LambdaSMEFT^2};

